### ISSUE TITLE
Browser hooked but commands not executed (NameError)

### ISSUE THREAD

**Issue by wvdongen** [beefproject/beef#1169]
First of all great job on beef!

I'm trying to hook an browser by uning an XSS in a flash app. The flash app reads in an XML file where URL can be set to "javascript:etc".

The browser does appear in the hooked browser list in beef prepended with 2 question marks, and the hooked browser also sends ajax poll requests. However, commands do not seem to get executed on the hooked browser. 

Beef keep continuously outputting the following:
```
NameError - uninitialized constant Play_sound:
        /usr/share/beef-xss/core/main/handlers/modules/command.rb:33:in `const_get'
        /usr/share/beef-xss/core/main/handlers/modules/command.rb:33:in `add_command_instructions'
        /usr/share/beef-xss/core/main/handlers/hookedbrowsers.rb:80:in `block (2 levels) in <class:HookedBrowsers>'
        /usr/lib/ruby/vendor_ruby/dm-core/collection.rb:508:in `block in each'
        /usr/lib/ruby/vendor_ruby/dm-core/support/lazy_array.rb:411:in `block in each'
        /usr/lib/ruby/vendor_ruby/dm-core/support/lazy_array.rb:411:in `each'
        /usr/lib/ruby/vendor_ruby/dm-core/support/lazy_array.rb:411:in `each'
        /usr/lib/ruby/vendor_ruby/dm-core/collection.rb:505:in `each'
        /usr/share/beef-xss/core/main/handlers/hookedbrowsers.rb:80:in `block in <class:HookedBrowsers>'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1603:in `call'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1603:in `block in compile!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:966:in `[]'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:966:in `block (3 levels) in route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:985:in `route_eval'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:966:in `block (2 levels) in route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1006:in `block in process_route'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1004:in `catch'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1004:in `process_route'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:964:in `block in route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:963:in `each'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:963:in `route!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1076:in `block in dispatch!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `block in invoke'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `catch'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `invoke'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1073:in `dispatch!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:898:in `block in call!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `block in invoke'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `catch'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:1058:in `invoke'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:898:in `call!'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:886:in `call'
        /usr/lib/ruby/vendor_ruby/rack/nulllogger.rb:9:in `call'
        /usr/lib/ruby/vendor_ruby/rack/head.rb:11:in `call'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:180:in `call'
        /usr/lib/ruby/vendor_ruby/sinatra/base.rb:2014:in `call'
        /usr/lib/ruby/vendor_ruby/rack/urlmap.rb:65:in `block in call'
        /usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `each'
        /usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `call'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:80:in `block in pre_process'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:78:in `catch'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:78:in `pre_process'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
        /usr/lib/ruby/vendor_ruby/thin/connection.rb:38:in `receive_data'
        /usr/lib/ruby/vendor_ruby/eventmachine.rb:187:in `run_machine'
        /usr/lib/ruby/vendor_ruby/eventmachine.rb:187:in `run'
        /usr/lib/ruby/vendor_ruby/thin/backends/base.rb:61:in `start'
        /usr/lib/ruby/vendor_ruby/thin/server.rb:159:in `start'
        /usr/share/beef-xss/core/main/server.rb:127:in `start'
        ./beef:145:in `<main>'
```
Is this a bug? Or am I doing something wrong?

Using beef 0.4.6.1-alpha

**Comment by wvdongen** [comment]
After removing the beef.db everything worked as expected
