### ISSUE TITLE
Error with beef-strike and Armitage

### ISSUE THREAD

**Issue by rayluch** [beefproject/beef#1283]
![screenshot - 250716 - 01 39 03](https://cloud.githubusercontent.com/assets/20630883/17087369/a5eadbba-5208-11e6-9e4d-16d7fdcdd53b.png)
![screenshot - 250716 - 01 44 21](https://cloud.githubusercontent.com/assets/20630883/17087411/5aca8a4e-5209-11e6-9779-6ae8ef299741.png)

I have the lastest Beef, I load msfconsole and use msgrpc, I start beef and it works so far but when I open armitage and I try to connect to beef, this happens. It doesn't end, it keeps doing that at least for 10 minutes (I usually terminate the program).

What can I do to fix it? I have seen 1 thread with the same problem and there was no answer.

I have tried a different thing too, using Armitage directly without msfconsole. I start ./beef and connect to it and "it works" (at least it says it does), but it wont load zombies and it doesn't work in general.

This is what happens when I try to input any command:

[-] DatabaseImpl.java - exception: ERROR: invalid input syntax for type inet: "null"
org.postgresql.util.PSQLException: ERROR: invalid input syntax for type inet: "null"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:302)
	at msf.DatabaseImpl.executeUpdate(DatabaseImpl.java:109)
	at msf.DatabaseImpl.execute(DatabaseImpl.java:594)
	at msf.RpcConnectionImpl.execute(RpcConnectionImpl.java:140)
	at msf.RpcQueue.processRequest(RpcQueue.java:33)
	at msf.RpcQueue.run(RpcQueue.java:83)
	at java.lang.Thread.run(Thread.java:745)

No matter what I do, the same error message :(.

**Comment by antisnatchor** [comment]
This isn't a bug in BeEF, but rather a bug in the Armitage API, or whatever is connecting to BeEF parsing the RESTful API JSON responses.

Looks like the Armitage JSON parser is expecting some fields which are not what the BEEF API is returning.
