### ISSUE TITLE
 TypeError - no implicit conversion of nil into String

### ISSUE THREAD

**Issue by rlfree** [beefproject/beef#1349]
#### Environment

What version/revision of BeEF are you using?
beEF Version: 0.4.7.0-alpha
Ruby Version: ruby 2.2.6p396 

Happens on IE, Firefox, Chrome

On what operating system?
Ubuntu 16.04 Xenial

The only config changes I made were to my hostname and port (port forwarding rules were all adding in the router configuration). The Host Name / Domain Name section was also set with a public IP (port forwarding rules were all added in the router configuration as well).

Happens with both the Metasploit extension enabled and disabled.

#### Summary

When I select a command to execute on a hooked browser (doesn't matter what command) I receive no command results. On the cli where I started beEF it runs the following error over and over (basically until I stop the beEF server), which makes me believe it might be a Ruby config problem:

[11:31:39][*] File [/modules/host/get_system_info/getSystemInfo.class] bound to Url [/getSystemInfo.class] using Content-type [application/java-vm]
2017-02-02 11:31:39 - **TypeError - no implicit conversion of nil into String:**
	/opt/beef/core/main/network_stack/websocket/websocket.rb:32:in `+'
	/opt/beef/core/main/network_stack/websocket/websocket.rb:32:in `initialize'
	/usr/lib/ruby/2.2.0/singleton.rb:141:in `new'
	/usr/lib/ruby/2.2.0/singleton.rb:141:in `block in instance'
	/usr/lib/ruby/2.2.0/singleton.rb:139:in `synchronize'
	/usr/lib/ruby/2.2.0/singleton.rb:139:in `instance'
	/opt/beef/core/main/handlers/modules/command.rb:43:in `add_command_instructions'
	/opt/beef/core/main/handlers/hookedbrowsers.rb:80:in `block (2 levels) in <class:HookedBrowsers>'
	/var/lib/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/collection.rb:508:in `block in each'
	/var/lib/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `block in each'
	/var/lib/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `each'
	/var/lib/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/support/lazy_array.rb:411:in `each'
	/var/lib/gems/2.2.0/gems/dm-core-1.2.1/lib/dm-core/collection.rb:505:in `each'
	/opt/beef/core/main/handlers/hookedbrowsers.rb:80:in `block in <class:HookedBrowsers>'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/var/lib/gems/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/var/lib/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
	/var/lib/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
	/var/lib/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
	/var/lib/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
	/var/lib/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/var/lib/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/var/lib/gems/2.2.0/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
	/var/lib/gems/2.2.0/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
	/opt/beef/core/main/server.rb:125:in `start'
	./beef:165:in `<main>'

#### Expected Behaviour
The expected behavior should be running the command successfully on the browser.

#### Actual Behaviour
No results from running a command.

#### Steps to Reproduce
Clone beEf from github.
Install per instructions on Ubuntu 16.04

Run the beEF executable with either the ruby command or ./ command. Results remain the same each time.

**Comment by rlfree** [comment]
It looks like this issue was caused when trying to integrate beEF with King Phisher. The King Phisher server is set up with SSL certs and I was attempting to use beEF with HTTPS disabled. Enabling HTTPS in the config file fixed this.

Is there anyway to use two different SSL certs? I have two FQDNs that are pointed to the same IP address. Each domain is used for a different phishing approach for our clients. I would like to be able to use the different certs on the fly depending on what link is provided in the email that is sent to the client.
