### ISSUE TITLE
There was an error while trying to load the gem 'uglifier'

### ISSUE THREAD

**Issue by greencopper** [beefproject/beef#1502]
I am using master on Arch Linux with ruby version 2.5.0. I have run bundle and have installed all the gems. I get the following error:

```
$ ruby beef
Traceback (most recent call last):
	10: from beef:44:in `<main>'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /home/foo/tmp/beef/core/loader.rb:10:in `<top (required)>'
	 6: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
	 5: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
	 4: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
	 3: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
	 2: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
	 1: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
/usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'uglifier'. (Bundler::GemRequireError)
Gem Load Error is: wrong argument type Class (expected Module)
Backtrace for gem load error is:
/usr/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `include'
/usr/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `class_eval'
/usr/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `block in <top (required)>'
/usr/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `each'
/usr/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `<top (required)>'
/usr/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `require'
/usr/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `<top (required)>'
/usr/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `require'
/usr/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `available?'
/usr/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `each'
/usr/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `find'
/usr/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `best_available'
/usr/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:57:in `autodetect'
/usr/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/usr/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/usr/lib/ruby/gems/2.5.0/gems/uglifier-3.2.0/lib/uglifier.rb:5:in `require'
/usr/lib/ruby/gems/2.5.0/gems/uglifier-3.2.0/lib/uglifier.rb:5:in `<top (required)>'
/usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/usr/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/home/foo/tmp/beef/core/loader.rb:10:in `<top (required)>'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
beef:44:in `<main>'
Bundler Error Backtrace:
```

**Comment by bcoles** [comment]
BeEF hasn't been tested on Ruby 2.5.

The issue is probably related to the `therubyracer` gem. Was the gem installed during `bundle install` ? Which version is in `Gemfile.lock` ?

You can try removing the `Gemfile.lock` file, then changing the version of `therubyracer` in `Gemfile` to `0.12.3`, then do `bundle install`.

**Comment by greencopper** [comment]
Thanks. Changing the version of `therubyracer` worked.
