### ISSUE TITLE
cant start beef

### ISSUE THREAD

**Issue by slavadba** [beefproject/beef#1547]
Possible my issue similar to https://github.com/beefproject/beef/issues/1540 - but I not sure.

#### Environment

What version/revision of BeEF are you using?
I cant start BeEF - but in config.yaml I see 0.4.7.0-alpha.

On what version of Ruby?
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

On what browser?
n/a

On what operating system?
Kali 2018

#### Configuration

Are you using a non-default configuration?
no
Have you enabled or disabled any BeEF extensions?
no

#### Summary

root@kali:/lib/live/mount/persistence/sdb3/beef-xss# ./beef
Traceback (most recent call last):
	5: from ./beef:32:in `<main>'
	4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	2: from /lib/live/mount/persistence/sdb3/beef-xss/core/loader.rb:14:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- xmlrpc/client (LoadError)
root@kali:/lib/live/mount/persistence/sdb3/beef-xss# less /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb
root@kali:/lib/live/mount/persistence/sdb3/beef-xss# vi /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb
root@kali:/lib/live/mount/persistence/sdb3/beef-xss#

#### Expected Behaviour
start BeEF

**Comment by bcoles** [comment]
It looks like `xmlrpc/client` was added to the BeEF loader by the Kali team.

That said, I can't reproduce this issue on Kali 2018 using either the packaged version or the version of BeEF from Github.

`/lib/live/mount/persistence/sdb3/` indicates you might be running of a live USB?

Also, you may run into issues with Ruby 2.5.x.

**Comment by slavadba** [comment]
"/lib/live/mount/persistence/sdb3/ indicates you might be running of a live USB?" - Yes, that's it.
 I tried to install the newest version of BeEF (installed with git clone https://github.com/beefproject/beef and then ./install) and it seems that I got the same error :

/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'

or is it something else already and it may be better to create a separate topic? The whole output from console:
.
.
.
[INFO]  Install completed successfully!
[INFO]  Run './beef' to launch BeEF

==========================================

root@kali:~/beef# ./beef
Traceback (most recent call last):
	10: from ./beef:44:in `<main>'
	 9: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /root/beef/core/loader.rb:10:in `<top (required)>'
	 6: from /usr/lib/ruby/vendor_ruby/bundler.rb:108:in `require'
	 5: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in `require'
	 4: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in `each'
	 3: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `block in require'
	 2: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `each'
	 1: from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'uglifier'. (Bundler::GemRequireError)
Gem Load Error is: wrong argument type Class (expected Module)
Backtrace for gem load error is:
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:23:in `include'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:23:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:22:in `class_eval'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:22:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:21:in `each'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:21:in `<top (required)>'
/var/lib/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `require'
/var/lib/gems/2.5.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `<top (required)>'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `require'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `available?'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `each'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `find'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `best_available'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:57:in `autodetect'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
/var/lib/gems/2.5.0/gems/uglifier-4.1.10/lib/uglifier.rb:5:in `require'
/var/lib/gems/2.5.0/gems/uglifier-4.1.10/lib/uglifier.rb:5:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:82:in `require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:82:in `block (2 levels) in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `block in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in `require'
/usr/lib/ruby/vendor_ruby/bundler.rb:108:in `require'
/root/beef/core/loader.rb:10:in `<top (required)>'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
./beef:44:in `<main>'
Bundler Error Backtrace:
root@kali:~/beef#

**Comment by bcoles** [comment]
This is a different error.

`/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'uglifier'`

Your issue is the uglifier gem.

**Comment by slavadba** [comment]
Can I somehow fix this?

**Comment by bcoles** [comment]
Probably.

You'll need to remove `Gemfile.lock`.

Then edit `Gemfile`

There's a conditional statement for `therubyracer` - change `0.12.2` to `0.12.3`

**Comment by bcoles** [comment]
Alternatively, I've fixed this in 903f3bf9984cf4c92d6a5e99f3768de99d05adb4.

You can do a `git pull` then `bundle install` and should hopefully fix your issue.

**Comment by wlamraoui** [comment]
the simple way i solved this was by commenting  `require 'xmlrpc/client' ` in  `loader.rb` file in folder core  
```
require 'base64'
#require 'xmlrpc/client'
require 'openssl'
```

**Comment by wlamraoui** [comment]
the simple way i solved this was : 

```
$> gem install xmlrpc 

```
