### ISSUE TITLE
How to Run beef ?

### ISSUE THREAD

**Issue by thesalah1212** [beefproject/beef#1557]
to Run beef command I need to change directory then `./beef `
I want to run it by simply typing `beef` in the command line so I change Path Environment variable
but I got this error 
```
thesalah1212@thesalah1212-Satellite:~$ beef
/home/thesalah1212/beef/core/loader.rb:10:in `<top (required)>': private method `require' called for Bundler:Module (NoMethodError)
	from /usr/local/lib/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/thesalah1212/beef/beef:44:in `<main>'
```

**Comment by bcoles** [comment]
You can't. See #1466 for a solution.
