### ISSUE TITLE
Add Configuration File Validation and Error Handling

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1739]
BeEF should validate the configuration file options and exit upon failure.

Each extension should be able to define it's own validation for configuration file options, which is called upon extension soft load.

This is especially important to prevent issues arising due to changes to the configuration file which affect backwards compatibility.

**Comment by leedhar** [comment]
:/usr/share/beef-xss# ./beef
[21:08:24][!] Fatal Error: cannot load configuration file
Traceback (most recent call last):
	5: from ./beef:62:in `<main>'
	4: from ./beef:62:in `new'
	3: from /usr/share/beef-xss/core/main/configuration.rb:26:in `initialize'
	2: from /usr/share/beef-xss/core/main/configuration.rb:34:in `rescue in initialize'
	1: from /usr/share/beef-xss/core/ruby/print.rb:35:in `print_debug'
/usr/share/beef-xss/core/main/configuration.rb:16:in `instance': uninitialized class variable @@instance in BeEF::Core::Configuration (NameError)
am getting this error

**Comment by bcoles** [comment]
@leedhar is there more to that error message? `Fatal Error: cannot load configuration file` appears exactly once in the framework, and it should print more information, such as the configuration file path:

```ruby
print_error "Fatal Error: cannot load configuration file '#{config}' : #{e.message}"
```

Are you using the latest version of BeEF?
