### ISSUE TITLE
[ARE] ERROR after ARE checked

### ISSUE THREAD

**Issue by Akityo** [beefproject/beef#1752]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.2).

#### Environment

What version/revision of BeEF are you using?

0.4.7.3-alpha

On what version of Ruby?
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
also tested on 
ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-linux]

On what browser?

Chrome for Mac 75.0.3770.142

On what operating system?

MAC 10.12.6

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

ARE alert script

#### Actual Behaviour

What was the actual result?

null

#### Steps to Reproduce

Please provide steps to reproduce this issue.
[20:20:08][>] [INIT] Processing Browser Details...
[20:20:08][>] Event: 198.13.59.138 just joined the horde from the domain: 0x1.club:8080
[20:20:08][>] Event: 198.13.59.138 is connecting from: {"city"=>{"geoname_id"=>6419435, "names"=>{"en"=>"Heiwajima", "ja"=>"平和島"}}, "continent"=>{"code"=>"AS", "geoname_id"=>6255147, "names"=>{"de"=>"Asien", "en"=>"Asia", "es"=>"Asia", "fr"=>"Asie", "ja"=>"アジア", "pt-BR"=>"Ásia", "ru"=>"Азия", "zh-CN"=>"亚洲"}}, "country"=>{"geoname_id"=>1861060, "iso_code"=>"JP", "names"=>{"de"=>"Japan", "en"=>"Japan", "es"=>"Japón", "fr"=>"Japon", "ja"=>"日本", "pt-BR"=>"Japão", "ru"=>"Япония", "zh-CN"=>"日本"}}, "location"=>{"accuracy_radius"=>1000, "latitude"=>35.5826, "longitude"=>139.7459, "time_zone"=>"Asia/Tokyo"}, "postal"=>{"code"=>"143-0006"}, "registered_country"=>{"geoname_id"=>1861060, "iso_code"=>"JP", "names"=>{"de"=>"Japan", "en"=>"Japan", "es"=>"Japón", "fr"=>"Japon", "ja"=>"日本", "pt-BR"=>"Japão", "ru"=>"Япония", "zh-CN"=>"日本"}}, "subdivisions"=>[{"geoname_id"=>1850144, "iso_code"=>"13", "names"=>{"en"=>"Tokyo", "fr"=>"Préfecture de Tokyo", "ja"=>"東京都"}}]}
[20:20:08][>] Browser has updated 'location.city' to 'Heiwajima'
[20:20:08][>] Browser has updated 'location.country' to 'Japan'
[20:20:08][!] [Browser Details] Invalid browser version returned from the hook browser's initial connection.
[20:20:08][>] Event: 198.13.59.138 appears to have come back online
[20:20:08][>] Event: IP address has changed from 198.13.59.138 to 153.122.96.88
153.122.96.88 - - [30/Jul/2019:20:20:08 +0000] "GET /app.js?BEET=w0FKkyPqzIhkYkfralHPF4O6sOSE9HhRxc6EMOe9GijRsVdMQRTxHR6gVklhdkzNwNw0s6uwILchcit2&_=1564518008333 HTTP/1.1" 200 - 0.0385
[20:20:08][*] New Hooked Browser [id:28, ip:********, browser:C-75.0.3770.142, os:OSX-], hooked domain [0x1.club:8080]
[20:20:08][>] Hooked browser has network interface 127.0.0.1
[20:20:08][*] [ARE] Checking if any defined rules should be triggered on target.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: LAN HTTP Scan (Common IPs).
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Raw JavaScript.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Start CoinHive JavaScript miner.
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: LAN CORS Scan.
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Collects multiple snapshots of the webpage within Same-Origin.
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: LAN Fingerprint.
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: LAN Flash Scan.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: LAN Fingerprint (Common IPs).
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Get Cookie.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Confirm Close Tab.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Perform Man-In-The-Browser.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: LAN CORS Scan (Common IPs).
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: LAN Flash Scan (Common IPs).
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: LAN HTTP Scan.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Browser version check -> (hook) 75.0.3770.142 ALL (rule) : true
[20:20:08]    |_  OS version check -> (hook)  ALL (rule): true
[20:20:08]    |_  Hooked browser and OS type/version MATCH rule: Display an alert.
[20:20:08]    |_  Found [28/37] ARE rules matching the hooked browser type/version.
[20:20:08][!] uninitialized constant BeEF::Core::Command::Get_http_servers
[20:20:08][>] /usr/share/beef-xss/core/main/autorun_engine/engine.rb:284:in `prepare_command'
/usr/share/beef-xss/core/main/autorun_engine/engine.rb:68:in `block (2 levels) in trigger'
/usr/share/beef-xss/core/main/autorun_engine/engine.rb:59:in `each'
/usr/share/beef-xss/core/main/autorun_engine/engine.rb:59:in `block in trigger'
/usr/share/beef-xss/core/main/autorun_engine/engine.rb:43:in `each'
/usr/share/beef-xss/core/main/autorun_engine/engine.rb:43:in `trigger'
/usr/share/beef-xss/core/main/autorun_engine/engine.rb:33:in `run'
/usr/share/beef-xss/core/main/handlers/browserdetails.rb:513:in `setup'
/usr/share/beef-xss/core/main/handlers/browserdetails.rb:19:in `initialize'
/usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `new'
/usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `execute'
/usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:80:in `block in check_packets'
/usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `each'
/usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `check_packets'
/usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:48:in `block (2 levels) in <class:DynamicReconstruction>'
#<Thread:0x00007f289c6f0c68@/usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:47 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	12: from /usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:48:in `block (2 levels) in <class:DynamicReconstruction>'
	11: from /usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `check_packets'
	10: from /usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `each'
	 9: from /usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:80:in `block in check_packets'
	 8: from /usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `execute'
	 7: from /usr/share/beef-xss/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `new'
	 6: from /usr/share/beef-xss/core/main/handlers/browserdetails.rb:19:in `initialize'
	 5: from /usr/share/beef-xss/core/main/handlers/browserdetails.rb:513:in `setup'
	 4: from /usr/share/beef-xss/core/main/autorun_engine/engine.rb:33:in `run'
	 3: from /usr/share/beef-xss/core/main/autorun_engine/engine.rb:43:in `trigger'
	 2: from /usr/share/beef-xss/core/main/autorun_engine/engine.rb:43:in `each'
	 1: from /usr/share/beef-xss/core/main/autorun_engine/engine.rb:81:in `block in trigger'
/usr/share/beef-xss/core/main/autorun_engine/engine.rb:117:in `prepare_sequential_wrapper': undefined method `[]' for true:TrueClass (NoMethodError)

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by bcoles** [comment]
Strange, looks like it's failing with `uninitialized constant BeEF::Core::Command::Get_http_servers`. That shouldn't happen, and may be a bug.

As an aside, it looks like you have a large number of autorun rules enabled (37!). That is not advisable. All autorun rules will run automatically upon hook. Having a large number of autorun rules can cause issues, as they will all execute simultaneously. This may induce high CPU load for a short period. This can introduce issues for modules which require timing and work best with minimum network/CPU load.

Similarly, several of the selected autorun rules make use of multiple outbound HTTP requests on top of the hook polling. Browsers usually have a hard cap on the maximum number of concurrent HTTP requests. Issuing too many requests concurrently will cause some requests to start failing.

The ARE rules provided in the `arerules` directory are examples. You can use a few of them simultaneously, however, if you want to execute multiple modules, it's generally better to group them together into a few ARE rules, and chain the modules together sequentially using the `sequential` ARE rule directive.

Additionally, having multiple module execute simultaneously on top of the hook polling results in a large number of requests to the BeEF server. If you're using SQLite as the datastore, you may run into database locking issues, as SQLite does not support concurrent writes.

I also noticed you're using the CoinHive miner ARE rule.

```
[20:20:08] |_ Hooked browser and OS type/version MATCH rule: Start CoinHive JavaScript miner.
[20:20:08] |_ OS version check -> (hook) ALL (rule): true
```

That module since been removed from the framework, as CoinHive no longer exists.
