### ISSUE TITLE
Bug when click delete zombie

### ISSUE THREAD

**Issue by Hotsunrize** [beefproject/beef#1859]
when i click delete zombie
![image](https://user-images.githubusercontent.com/24307070/72657140-875f1d00-39db-11ea-8873-096ce8ce4c94.png)

i got error infomation like this

```
2020-01-18 02:12:37 - ArgumentError - wrong number of arguments (given 0, expected 1):
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/activerecord-6.0.2.1/lib/active_record/persistence.rb:325:in `destroy'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:106:in `public_send'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:106:in `block in method_missing'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/activerecord-6.0.2.1/lib/active_record/relation.rb:398:in `block in scoping'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/activerecord-6.0.2.1/lib/active_record/relation.rb:773:in `_scoping'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/activerecord-6.0.2.1/lib/active_record/relation.rb:398:in `scoping'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:106:in `method_missing'
	/root/beef/core/main/rest/handlers/hookedbrowsers.rb:44:in `block in <class:HookedBrowsers>'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-2.1.1/lib/rack/null_logger.rb:11:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-2.1.1/lib/rack/head.rb:14:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-2.1.1/lib/rack/urlmap.rb:77:in `block in call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-2.1.1/lib/rack/urlmap.rb:61:in `each'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-2.1.1/lib/rack/urlmap.rb:61:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/root/beef/core/main/server.rb:165:in `start'
	./beef:232:in `<main>'

```

**Comment by bcoles** [comment]
Confirmed.

```
2020-01-18 03:55:49 - ArgumentError - wrong number of arguments (given 0, expected 1):
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/persistence.rb:325:in `destroy'
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:106:in `public_send'
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:106:in `block in method_missing'
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation.rb:398:in `block in scoping'
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation.rb:773:in `_scoping'
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation.rb:398:in `scoping'
	/var/lib/gems/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:106:in `method_missing'
	/root/Desktop/beef/core/main/rest/handlers/hookedbrowsers.rb:44:in `block in <class:HookedBrowsers>'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.1.1/lib/rack/null_logger.rb:11:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.1.1/lib/rack/head.rb:14:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.1.1/lib/rack/urlmap.rb:77:in `block in call'
	/var/lib/gems/2.5.0/gems/rack-2.1.1/lib/rack/urlmap.rb:61:in `each'
	/var/lib/gems/2.5.0/gems/rack-2.1.1/lib/rack/urlmap.rb:61:in `call'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/var/lib/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/var/lib/gems/2.5.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/root/Desktop/beef/core/main/server.rb:165:in `start'
	./beef:232:in `<main>'
```

**Comment by jcrew99** [comment]
#1863 This should fix it, @bcoles can you please review it and i will make a test case for it.

**Comment by bcoles** [comment]
#1863 appears to have resolved this issue, althoguh I haven't reviewed the code.
