### ISSUE TITLE
NameError - uninitialized constant BeEF::Core::Command::Simple_hijacker:

### ISSUE THREAD

**Issue by ptahchiev** [beefproject/beef#1865]
I have cloned beef from the master branch in github. Installed it on Ubunti linux and when I run it I get this:
```
2020-01-23 21:50:27 - NameError - uninitialized constant BeEF::Core::Command::Simple_hijacker:
	/root/workspace/beef/core/main/handlers/modules/command.rb:33:in `const_get'
	/root/workspace/beef/core/main/handlers/modules/command.rb:33:in `add_command_instructions'
	/root/workspace/beef/core/main/handlers/hookedbrowsers.rb:94:in `block (2 levels) in <class:HookedBrowsers>'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:85:in `each'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:85:in `each'
	/root/workspace/beef/core/main/handlers/hookedbrowsers.rb:94:in `block in <class:HookedBrowsers>'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
	/usr/local/rvm/gems/ruby-2.5.3@beef/gems/rack-2.1.1/lib/rack/null_logger.rb:11:in `call'
```

#### Environment

What version/revision of BeEF are you using?
master from github
On what version of Ruby?
root@ubuntu-s-1vcpu-1gb-ams2-01:~/workspace/beef# ruby --version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

On what browser?
Chrome
On what operating system?
Ubuntu Linux

#### Configuration

Are you using a non-default configuration?
no

Have you enabled or disabled any BeEF extensions?
no

**Comment by ptahchiev** [comment]
When I start beef this error keeps showing in the log over and over again. It seems like there's a cronjob or something that makes the error appear in the log.

**Comment by jcrew99** [comment]
@ptahchiev  Hi there,
Could you please add the entire output you get when you start beef?
Could you also try starting beef with the -x flag?

**Comment by jcrew99** [comment]
@ptahchiev  Have you had any luck with this?

**Comment by jcrew99** [comment]
Hi @ptahchiev  i am closing this ticket due to being inactive, please let me know if you have this issue again. Please feel free to re-open it

**Comment by UBISOFT-1** [comment]
@jcrew99  Thanks the `-x` flag solves the problem, just wanted to confirm, for any of you other `./beef -x` did the trick.

**Comment by UBISOFT-1** [comment]
btw, just if you were wondering, I was using Windows Subsystem for Linux and Ubuntu 20.04 with Ruby 2.7 I guess.
