### ISSUE TITLE
Unable to run Beef on Mac OS X Catalina

### ISSUE THREAD

**Issue by claudiobovio** [beefproject/beef#1901]
#### Environment

What version/revision of BeEF are you using?
0.5.0.0-alpha-pre

On what version of Ruby?
2.7.0-preview1

On what browser?

On what operating system?
Mac OsX Catalina

#### Configuration

Are you using a non-default configuration?
No

Have you enabled or disabled any BeEF extensions?
No
#### Summary

Please provide a summary of the issue.

Hello,
I'am trying to start beef on Mac OSx Catalina with bash shell but I have some issues.

-- migration_context()
   -> 0.0074s
[ 1:04:40][*] BeEF is loading. Wait a few seconds...
Traceback (most recent call last):
	24: from /Users/claudiobovio/beef/beef:184:in `<main>'
	23: from /Users/claudiobovio/beef/core/main/migration.rb:21:in `update_db!'
	22: from /Users/claudiobovio/beef/core/main/migration.rb:30:in `update_commands!'
	21: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/relation/calculations.rb:193:in `pluck'
	20: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/relation.rb:828:in `skip_query_cache_if_necessary'
	19: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/relation/calculations.rb:193:in `block in pluck'
	18: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1016:in `arel'
	17: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1071:in `build_arel'
	16: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1187:in `build_select'
	15: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1196:in `arel_columns'
	14: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1196:in `flat_map'
	13: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1196:in `each'
	12: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1199:in `block in arel_columns'
	11: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/relation/query_methods.rb:1216:in `arel_column'
	10: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/model_schema.rb:352:in `columns_hash'
	 9: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/model_schema.rb:477:in `load_schema'
	 8: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/2.7.0/monitor.rb:230:in `mon_synchronize'
	 7: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/model_schema.rb:480:in `block in load_schema'
	 6: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
	 5: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/attributes.rb:247:in `load_schema!'
	 4: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/model_schema.rb:490:in `load_schema!'
	 3: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/schema_cache.rb:82:in `columns_hash'
	 2: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/schema_cache.rb:76:in `columns'
	 1: from /Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:114:in `columns'
/Users/claudiobovio/.rbenv/versions/2.7.0-preview1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:358:in `table_structure': Could not find table 'command_modules' (ActiveRecord::StatementInvalid)

Thank you

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by jcrew99** [comment]
hi @claudiobovio, that doesnt look great, it seems like an activerecord issue, can you please confirm that you have pulled from latest master and please start beef with the -x flag.
" $ ./beef -x " 
Please let me know if you still have the same issue

**Comment by claudiobovio** [comment]
Hi @jcrew99, yes I think that is a activerecord issue but I don't know how fix it.
I have the same issue starting beef with the -x flag.
Thank you for your replay

**Comment by jcrew99** [comment]
@claudiobovio  I have been unable to get the same output so far or replicate your environment.
Just to check did you do:

`` 
./install? 
``
before you ran ./beef? 

Also what did you use to install ruby? 

if so can you please provide the terminal output (by running it again to check).
I know that we are going to update the install script so this might be something that relates to it.

Otherwise please try:
$ bundle install 

If that doesnt work, please answer the questions above and provide screenshots.
Can you also fill in the steps to reproduce section? 

Please detail any information from the start of the installation process to finish. 
It seems likely that its an install issue at this point but it will help me replicate it.

**Comment by DeezyE** [comment]
Closing issue due to inactivity, please reopen as needed
