### ISSUE TITLE
not worcking mac os

### ISSUE THREAD

**Issue by Astra321** [beefproject/beef#2081]
'
/Users/pc/beef/extensions/events/handler.rb:51:in `[]': no implicit conversion of String into Integer (TypeError)
#<Thread:0x00007fd5d4b19890 /Users/pc/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:47 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	11: from /Users/pc/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:48:in `block (2 levels) in <class:DynamicReconstruction>'
	10: from /Users/pc/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `check_packets'
	 9: from /Users/pc/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:55:in `each'
	 8: from /Users/pc/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:80:in `block in check_packets'
	 7: from /Users/pc/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `execute'
	 6: from /Users/pc/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:107:in `new'
	 5: from /Users/pc/beef/extensions/events/handler.rb:19:in `initialize'
	 4: from /Users/pc/beef/extensions/events/handler.rb:45:in `setup'
	 3: from /Users/pc/beef/extensions/events/handler.rb:45:in `each'
	 2: from /Users/pc/beef/extensions/events/handler.rb:46:in `block in setup'
	 1: from /Users/pc/beef/extensions/events/handler.rb:51:in `parse'
/Users/pc/beef/extensions/events/handler.rb:51:in `[]': no implicit conversion of String into Integer (TypeError)

**Comment by wheatley** [comment]
hi @Astra321 
would it be possible to post some further information regarding your environment setup and the steps you made before you got this error.
I will try and replicate this in the meantime and post some further information
thanks for the issue

**Comment by wheatley** [comment]
Marking stale as there has been limited activity over the last month.

**Comment by wheatley** [comment]
Closing due to lack of activity, please reopen if you need further assistance.
