### ISSUE TITLE
beef unable to install due to rubygem 

### ISSUE THREAD

**Issue by techarmy123** [beefproject/beef#2104]
# Submit Issue
i have been getting this issue again and again and i am unable to install beef 
[INFO]  Updating rubygems...
ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.
  help me out with this how i can reslove it and get beef install

**Comment by fel1x0u** [comment]
You need to install RubyGems and Ruby manually.

**Comment by bcoles** [comment]
Yeah I'm not sure what the issue is here, but it should be easy to work around.

The installer doesn't do a whole lot. It installs some operating system packages and installs some Ruby gems. This is fairly easy to do manually as fel1x0u suggested.

If you're using the git repository:

```
git clone https://github.com/beefproject/beef
cd beef
bundle install
```

That's it. If something fails please post the log and we can help out.

**Comment by techarmy123** [comment]
> You need to install RubyGems and Ruby manually.

thanks for the advise can you please tell me how to install both of them manually ?

**Comment by techarmy123** [comment]
now i am getting this error after instaling ruby manually 

Detecting Ruby environment...
Traceback (most recent call last):
        5: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
        4: from <internal:gem_prelude>:1:in `require'
        3: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1231:in `<top (required)>'
        2: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:1231:in `require'
        1: from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:67:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:93:in `singleton class': undefined method `default_specifications_dir' for class `#<Class:Gem>' (NameError)

**Comment by wheatley** [comment]
hey @techarmy123
I was wondering if you're still having issues with installing beef
If you are would you mind providing a few details of your current environment.
What happens with you run `ruby` in your terminal?

Thanks for the help @bcoles & @fel1x0u

**Comment by wheatley** [comment]
Closing due to lack of activity, please reopen if you need further assistance.

**Comment by Care00** [comment]
[INFO] Updating rubygems...
ERROR: Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.
this same error is repeating ,i tried some solutions but  none of em worked.
i am new to this knida stuff so plz help me out

**Comment by bcoles** [comment]
You should be able to do:

```
gem install bundler
bundle install
```

**Comment by Blackbeat47** [comment]
@bcoles if i do this it says
 
`An error occurred while installing xmlrpc (0.3.2), and Bundler cannot continue.`

**Comment by bcoles** [comment]
> @bcoles if i do this it says
> 
> `An error occurred while installing xmlrpc (0.3.2), and Bundler cannot continue.`

You'll have to mess around with the dependencies.

`rm Gemfile.lock` then `bundle install` and see what fails. In this example `xmlrpc, so `gem install xmlrpc`. Repeat `bundle install` and `gem install ____` until it works.
