### ISSUE TITLE
beef proxy

### ISSUE THREAD

**Issue by alter88** [beefproject/beef#2125]
#<Thread:0x0000559f89bf4590 /root/beef/extensions/proxy/proxy.rb:54 run> terminated with exception (report_on_exception is true):
/usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:210:in `block in wait_poll': could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use (ActiveRecord::ConnectionTimeoutError)
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:199:in `loop'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:199:in `wait_poll'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:160:in `internal_poll'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:286:in `internal_poll'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:155:in `block in poll'
        from /usr/local/rvm/rubies/ruby-3.0.0b/ruby/3.0.0/monitor.rb:202:in `synchronize'
        from /usr/local/rvm/rubies/ruby-3.0.0b/ruby/3.0.0/monitor.rb:202:in `mon_synchronize'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:164:in `synchronize'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:155:in `poll'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:870:in `acquire_connection'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_handling.rb:327:in `retrieve_connection'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/connection_handling.rb:283:in `connection'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/relation/delegation.rb:93:in `connection'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/relation/query_methods.rb:1394:in `preprocess_order_args'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/relation/query_methods.rb:360:in `order!'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/relation/query_methods.rb:355:in `order'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/relation/finder_methods.rb:583:in `ordered_relation'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/relation/finder_methods.rb:545:in `find_nth_with_limit'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/relation/finder_methods.rb:538:in `find_nth'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4b/active_record/relation/finder_methods.rb:122:in `first'
        from /root/beef/extensions/proxy/proxy.rb:196:in `get_tunneling_proxy'
        from /root/beef/extensions/proxy/proxy.rb:134:in `handle_request'

**Comment by wheatley** [comment]
hey @alter88 thanks for the issue, let me have a look into this error for you and get back to you.

**Comment by wheatley** [comment]
hey @alter88 looking to try and replicate your issue would you mind posting your current environment setup and possibly your configuration file?

**Comment by bcoles** [comment]
The stacktrace is related to ActiveRecord and may be similar to #2093.

However OP is using Ruby 3.0.0, which BeEF has not been tested with.

**Comment by jcrew99** [comment]
I'm not sure if this is the same error as #2093, that was more of the database connection not being established where this seems like a timeout. @alter88 can you provide the details that have been requested?

**Comment by wheatley** [comment]
Closing due to inactivity, please reopen if this is still an issue.
