### ISSUE TITLE
How do I disable SSL certificate validation in Firefox?

### ISSUE THREAD

**Issue by shuraros2334** [beefproject/beef#2135]
Good day.
I raised beef to vps and it works fine with certificate. That is, https://beef.com:443 works.

However, when I try to configure proxying through port 6789 with the same certificate. then it gives me an error:
#<Thread:0x0000562e0029fa98 /root/beef/extensions/proxy/proxy.rb:54 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /root/beef/extensions/proxy/proxy.rb:75:in `handle_request'
/root/beef/extensions/proxy/proxy.rb:75:in `accept': SSL_accept returned=1 errno=0 state=error: no shared cipher (OpenSSL::SSL::SSLError)

That is, he writes that the certificate is not suitable, although the site works over https. What could be the problem?

I am trying to forward a tunnel to the https domain: 
https://example.com

**Comment by shuraros2334** [comment]
#<Thread:0x00005617e4a490f0 /root/beef/extensions/proxy/proxy.rb:54 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /root/beef/extensions/proxy/proxy.rb:75:in `handle_request'
/root/beef/extensions/proxy/proxy.rb:75:in `accept': SSL_accept returned=1 errno=0 state=error: sslv3 alert bad certificate (OpenSSL::SSL::SSLError)


Traceback (most recent call last):
        4: from /root/beef/extensions/proxy/proxy.rb:77:in `handle_request'
        3: from /usr/lib/ruby/2.7.0/openssl/buffering.rb:253:in `readline'
        2: from /usr/lib/ruby/2.7.0/openssl/buffering.rb:300:in `eof?'
        1: from /usr/lib/ruby/2.7.0/openssl/buffering.rb:57:in `fill_rbuff'
/usr/lib/ruby/2.7.0/openssl/buffering.rb:57:in `sysread': SSL_read: sslv3 alert bad certificate (OpenSSL::SSL::SSLError)

**Comment by bcoles** [comment]
How are you using the proxy?

This works for me (note that `--proxy` uses `http://`) :

```
$ curl -isk --proxy http://127.0.0.1:6789/ https://127.0.0.1:3000/
```

Where `https://127.0.0.1:3000` is the hooked origin.

**Comment by shuraros2334** [comment]
Thanks, but for this you need to raise the local tunnel. How to do it via config.yaml on beef / extensions / proxy

my config.yaml:

beef:
    extension:
        proxy:
            name: 'Proxy'
            enable: true
            address: "beef.com"
            port: 6789
            authors: ["antisnatchor", "scotty"]
            key: "private.pem"
            cert: "public.pem"



> How are you using the proxy?
> 
> This works for me (note that `--proxy` uses `http://`) :
> 
> ```
> $ curl -isk --proxy http://127.0.0.1:6789/ https://127.0.0.1:3000/
> ```
> 
> Where `https://127.0.0.1:3000` is the hooked origin.

**Comment by bcoles** [comment]
You are using the self-signed certificates shipping with BeEF. You will need to accept the certificate warning or generate a certificate and ensure it is signed by a trusted certificate authority.

**Comment by shuraros2334** [comment]
I am using a certificate that is signed by a trusted certification authority. The problem is that when I access https://127.0.0.1:6789, I get a certificate error. And on http://127.0.0.1:6789 everything is fine. So it works through curl, but doesn't work in the browser. How can this be fixed in the browser?

> You are using the self-signed certificates shipping with BeEF. You will need to accept the certificate warning or generate a certificate and ensure it is signed by a trusted certificate authority.

**Comment by bcoles** [comment]
> The problem is that when I access https://127.0.0.1:6789

How are you accessing `https://127.0.0.1:6789` ? Can you show a screenshot?

**Comment by shuraros2334** [comment]
> > The problem is that when I access https://127.0.0.1:6789
> 
> How are you accessing `https://127.0.0.1:6789` ? Can you show a screenshot?

Forgive me for my stupidity. In firefox, the certificate is forcibly checked and when I access the example.com domain with my certificate signed on mydomainEvil.com, an error occurs. Do you know how to remove certificate verification?

**Comment by wheatley** [comment]
Closing due to inactivity, please reopen if this is still an issue.
