### ISSUE TITLE
Unknown Error: because i'm a beginner for beef

### ISSUE THREAD

**Issue by Jinghao1209** [beefproject/beef#2253]
### Description
What Error is this? When i use, somethings, its call this error until now...

### Error
```
2021-12-24 14:08:10 - NameError - uninitialized constant BeEF::Core::Command::S2c_dns_tunnel:
        /Users/JINGHAO/Dev/beef/core/main/handlers/modules/command.rb:33:in `const_get'
        /Users/JINGHAO/Dev/beef/core/main/handlers/modules/command.rb:33:in `add_command_instructions'
        /Users/JINGHAO/Dev/beef/core/main/handlers/hookedbrowsers.rb:114:in `block (2 levels) in <class:HookedBrowsers>'
        /Library/Ruby/Gems/2.6.0/gems/activerecord-6.1.4.4/lib/active_record/relation/delegation.rb:88:in `each'
        /Library/Ruby/Gems/2.6.0/gems/activerecord-6.1.4.4/lib/active_record/relation/delegation.rb:88:in `each'
        /Users/JINGHAO/Dev/beef/core/main/handlers/hookedbrowsers.rb:114:in `block in <class:HookedBrowsers>'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
        /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
        /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
        /Library/Ruby/Gems/2.6.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
        /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
        /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
        /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
        /Library/Ruby/Gems/2.6.0/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'
        /Library/Ruby/Gems/2.6.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'
        /Library/Ruby/Gems/2.6.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'
        /Library/Ruby/Gems/2.6.0/gems/thin-1.8.1/lib/thin/connection.rb:53:in `process'
        /Library/Ruby/Gems/2.6.0/gems/thin-1.8.1/lib/thin/connection.rb:39:in `receive_data'
        /Library/Ruby/Gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /Library/Ruby/Gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /Library/Ruby/Gems/2.6.0/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'
        /Library/Ruby/Gems/2.6.0/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'
        /Users/JINGHAO/Dev/beef/core/main/server.rb:158:in `start'
        ./beef:258:in `<main>'
```

**Comment by wheatley** [comment]
hey @Jinghao1209, happy holidays 

it looks like you're running a version of ruby that is unsupported.

if you upgrade ruby to 2.7.2 you should see this error disappear.

**Comment by jcrew99** [comment]
Hey @Jinghao1209, 
Did wheatley's suggestion solve the error?

**Comment by DeezyE** [comment]
Closed; inactivity
