### ISSUE TITLE
ERROR - E: Unable to correct problems, you have held broken packages. 

### ISSUE THREAD

**Issue by SGC-GamerZ** [beefproject/beef#2329]
## Summary

**Q:** Please provide a brief summary of the issue that you experienced.
**A: When I tried to install BeEF framework in debian 11 from the git repository, I got this error.

$ cd beef/
$ sudo ./install
$ #-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

-- [ BeEF Installer ] --

#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

[WARNING] This script will install BeEF and its required dependencies (including operating system packages).

Are you sure you wish to continue (Y/n)? Y

[INFO] Detecting OS...

[INFO] Operating System: Linux

[INFO] Launching Linux install...

[INFO] Detecting Linux OS distribution...

[INFO] OS Distribution: Debian

[INFO] Installing Debian prerequisite packages...

Hit:1 https://repo.skype.com/deb stable InRelease

Hit:2 http://downloads.metasploit.com/data/releases/metasploit-framework/apt lucid InRelease

Hit:3 http://security.debian.org/ bullseye-security InRelease

Hit:4 http://deb.debian.org/debian bullseye InRelease

Hit:5 https://download.docker.com/linux/debian bullseye InRelease

Hit:6 https://download.mono-project.com/repo/debian stable-buster InRelease

Hit:7 http://packages.microsoft.com/repos/code stable InRelease

Hit:8 http://deb.debian.org/debian-security bullseye-security InRelease

Hit:9 https://dl.winehq.org/wine-builds/debian bullseye InRelease

Hit:10 http://deb.debian.org/debian bullseye-updates InRelease

Hit:11 http://repository.spotify.com/ stable InRelease

Hit:12 https://deb.debian.org/debian experimental InRelease

Hit:13 https://download.cudo.org/repo/apt stable InRelease

Hit:14 https://download.sublimetext.com/ apt/stable/ InRelease

Hit:15 https://debmirror.hbcse.tifr.res.in/debian bullseye InRelease

Reading package lists... Done

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'

curl is already the newest version (7.74.0-1.3+deb11u1).

git is already the newest version (1:2.30.2-1).

openssl is already the newest version (1.1.1k-1+deb11u1).

openssl set to manually installed.

libsqlite3-0 is already the newest version (3.34.1-3).

libsqlite3-0 set to manually installed.

zlib1g is already the newest version (1:1.2.11.dfsg-2).

Some packages could not be installed. This may mean that you have

requested an impossible situation or if you are using the unstable

distribution that some required packages have not yet been created

or been moved out of Incoming.

The following information may help to resolve the situation:

The following packages have unmet dependencies:

g++ : Depends: cpp (= 4:10.2.1-1) but 4:12-20211211-1 is to be installed

gcc : Depends: cpp (= 4:10.2.1-1) but 4:12-20211211-1 is to be installed

libc6-dev : Depends: libc6 (= 2.31-13+deb11u2) but 2.34-0experimental2 is to be installed

Depends: libc-dev-bin (= 2.31-13+deb11u2)

E: Unable to correct problems, you have held broken packages.**

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version: latest**

2. **Ruby Version: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
**

3. **Browser Details (e.g. Chrome v81.0): Firefox 91.6.0esr (64-bit)**

4. **Operating System (e.g. OSX Catalina): Debian 11 86_64bit**

## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A: NO**

**Q:** Have you enabled or disabled any BeEF extensions?
**A: No**

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
<br /> To run beef-xss
**Actual Behaviour:**
<br /> did not run + throwed error of `you have held broken pakages`

## Steps to Reproduce

*Please provide steps to reproduce this issue.*

1. IDK

## Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be retrieved by following the instructions towards the top of the issue template.
![Screenshot from 2022-03-03 11-27-24](https://user-images.githubusercontent.com/79748628/156505269-2e6d4182-cb2d-4765-a326-4426e1283324.png)

**Comment by SGC-GamerZ** [comment]
PLease help me ASAP!!

**Comment by bcoles** [comment]
Are Ruby and Ruby Gems installed? (ie, do you have a `ruby` executable and `gem` executable?)

If so, you're probably fine. `cd` to the BeEF directory and run `gem install bundler && bundle install`. If that fails, post the logs.

**Comment by SGC-GamerZ** [comment]
> Are Ruby and Ruby Gems installed? (ie, do you have a `ruby` executable and `gem` executable?)
> 
> If so, you're probably fine. `cd` to the BeEF directory and run `gem install bundler && bundle install`. If that fails, post the logs.

$ sudo gem install bundler && bundle install
[sudo] password for root1: 
Fetching bundler-2.3.8.gem
Successfully installed bundler-2.3.8
Parsing documentation for bundler-2.3.8
Installing ri documentation for bundler-2.3.8
Done installing documentation for bundler after 0 seconds
1 gem installed
Fetching gem metadata from https://rubygems.org/.......
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/2.7.0
  /var/lib/gems/2.7.0/build_info
  /var/lib/gems/2.7.0/cache
  /var/lib/gems/2.7.0/doc
  /var/lib/gems/2.7.0/extensions
  /var/lib/gems/2.7.0/gems
  /var/lib/gems/2.7.0/plugins
  /var/lib/gems/2.7.0/specifications
Fetching rake 13.0.6


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
Installing rake 13.0.6
Fetching concurrent-ruby 1.1.9
Installing concurrent-ruby 1.1.9
Fetching i18n 1.10.0
Installing i18n 1.10.0
Fetching minitest 5.15.0
Installing minitest 5.15.0
Fetching tzinfo 2.0.4
Installing tzinfo 2.0.4
Fetching activesupport 7.0.2.2
Installing activesupport 7.0.2.2
Fetching activemodel 7.0.2.2
Installing activemodel 7.0.2.2
Fetching activerecord 7.0.2.2
Installing activerecord 7.0.2.2
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Fetching addressable 2.8.0
Installing addressable 2.8.0
Fetching ansi 1.5.0
Installing ansi 1.5.0
Fetching ast 2.4.2
Installing ast 2.4.2
Fetching fiber-local 1.0.0
Installing fiber-local 1.0.0
Fetching console 1.13.1
Installing console 1.13.1
Fetching nio4r 2.5.8
Installing nio4r 2.5.8 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/tmp/bundler20220303-20003-1teq21gnio4r-2.5.8/gems/nio4r-2.5.8/ext/nio4r
/usr/bin/ruby2.7 -I /usr/lib/ruby/vendor_ruby -r
./siteconf20220303-20003-1fj1iuj.rb extconf.rb
checking for unistd.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.7
	--with-unistd-dir
	--without-unistd-dir
	--with-unistd-include
	--without-unistd-include=${unistd-dir}/include
	--with-unistd-lib
	--without-unistd-lib=${unistd-dir}/lib
/usr/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an
executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.7.0/mkmf.rb:613:in `try_cpp'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1124:in `block in have_header'
	from /usr/lib/ruby/2.7.0/mkmf.rb:971:in `block in checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:361:in `block in postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:331:in `open'
	from /usr/lib/ruby/2.7.0/mkmf.rb:357:in `postpone'
	from /usr/lib/ruby/2.7.0/mkmf.rb:970:in `checking_for'
	from /usr/lib/ruby/2.7.0/mkmf.rb:1123:in `have_header'
	from extconf.rb:15:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/tmp/bundler20220303-20003-1teq21gnio4r-2.5.8/extensions/x86_64-linux/2.7.0/nio4r-2.5.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/tmp/bundler20220303-20003-1teq21gnio4r-2.5.8/gems/nio4r-2.5.8 for inspection.
Results logged to
/tmp/bundler20220303-20003-1teq21gnio4r-2.5.8/extensions/x86_64-linux/2.7.0/nio4r-2.5.8/gem_make.out

An error occurred while installing nio4r (2.5.8), and Bundler cannot
continue.
Make sure that `gem install nio4r -v '2.5.8' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  async-dns was resolved to 1.3.0, which depends on
    async-io was resolved to 1.32.2, which depends on
      async was resolved to 1.30.1, which depends on
        nio4r


this came now!!!!

**Comment by bcoles** [comment]
Try this:

```
sudo apt-get install ruby-dev zlib1g-dev liblzma-dev
```

Then `bundle install`

**Comment by SGC-GamerZ** [comment]
> Try this:
> 
> ```
> sudo apt-get install ruby-dev zlib1g-dev liblzma-dev
> ```
> 
> Then `bundle install`.
> 
> If that doesn't work, see if there's any hints in `/tmp/*/extensions/x86_64-linux/2.7.0/nio4r-2.5.8/mkmf.log`.

~$ sudo apt-get install ruby-dev zlib1g-dev liblzma-dev
[sudo] password for root1: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ruby-dev is already the newest version (1:2.7+2).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Depends: libc6 (= 2.31-13+deb11u2) but 2.34-0experimental2 is to be installed
             Depends: libc-dev-bin (= 2.31-13+deb11u2)
E: Unable to correct problems, you have held broken packages.
~$ bundle install
Could not locate Gemfile
![Screenshot from 2022-03-03 14-45-09](https://user-images.githubusercontent.com/79748628/156533927-53894c18-c577-4994-9f4b-9d9c6ab36f07.png)

**Comment by bcoles** [comment]
> ~$ bundle install
> Could not locate Gemfile

`bundle install` needs to be run from the BeEF directory.

Now that you have `ruby-dev` installed, if you're lucky you may be able to proceed.

But you'll likely need to fix your packages.

https://stackoverflow.com/questions/30451939/cant-install-libc6-package


```
Do

sudo apt-get autoclean
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -u dist-upgrade

Then run

sudo dpkg --configure -a
sudo apt-get -f install

If it works, then fine. or again try doing

sudo apt-get install libc6 libc6-dev
```

**Comment by SGC-GamerZ** [comment]
> > ~$ bundle install
> > Could not locate Gemfile
> 
> `bundle install` needs to be run from the BeEF directory.
> 
> Now that you have `ruby-dev` installed, if you're lucky you may be able to proceed.
> 
> But you'll likely need to fix your packages.
> 
> https://stackoverflow.com/questions/30451939/cant-install-libc6-package
> 
> ```
> Do
> 
> sudo apt-get autoclean
> sudo apt-get update
> sudo apt-get upgrade
> sudo apt-get -u dist-upgrade
> 
> Then run
> 
> sudo dpkg --configure -a
> sudo apt-get -f install
> 
> If it works, then fine. or again try doing
> 
> sudo apt-get install libc6 libc6-dev
> ```

![Screenshot from 2022-03-04 10-05-41](https://user-images.githubusercontent.com/79748628/156700196-156580b7-ea43-4b04-ac93-046b4d3c8f2b.png)

**DID NOT WORK**

**Comment by bcoles** [comment]
> DID NOT WORK

What happens when you run `bundle install` ?

**Comment by SGC-GamerZ** [comment]
> > DID NOT WORK
> 
> What happens when you run `bundle install` ?

![Screenshot from 2022-03-04 10-22-32](https://user-images.githubusercontent.com/79748628/156701677-aba74e8d-3b28-485a-8a56-ad339bdf1e5f.png)
![Screenshot from 2022-03-04 10-22-41](https://user-images.githubusercontent.com/79748628/156701683-7493aabf-4cfc-4419-b509-2dded31c42a5.png)
![Screenshot from 2022-03-04 10-22-49](https://user-images.githubusercontent.com/79748628/156701686-35f2029b-a967-4588-b899-d9b7cf24413a.png)

This all happens!!

**Comment by bcoles** [comment]
> This all happens!!

Are there any hints in the `mkmf.log` file?

**Comment by SGC-GamerZ** [comment]
> > 
> 
> Are there any hints in the `mkmf.log` file?

where is it located?

**Comment by bcoles** [comment]
> > > 
> > 
> > 
> > Are there any hints in the `mkmf.log` file?
> 
> where is it located?

![mkmf.log](https://user-images.githubusercontent.com/434827/156702236-cc453a75-d03b-49ee-96e9-e24a8e8f0b79.png)

**Comment by SGC-GamerZ** [comment]
> > This all happens!!
> 
> Are there any hints in the `mkmf.log` file?
![Screenshot from 2022-03-04 10-32-32](https://user-images.githubusercontent.com/79748628/156702556-4eda9d57-85c6-4826-b2b3-5d041601345c.png)


it says no such file or directory

**Comment by bcoles** [comment]
I tested a fairly clean Debian 11 build. `bundle install` worked fine for `nior4` then failed for sqlite (which makes sense because I hadn't installed the sqlite libs yet).

Apart from `git`, all I had installed was:

```
apt-get install build-essential
```

Perhaps that will help, as nior4 is failing to build, possibly due to missing `make` (part of `build-essential`).

I managed to break my packages while messing around. I'll let you know when I get it working.

**Comment by bcoles** [comment]
I used the nuclear option to fix packages.

```
sudo rm -rf /var/lib/dpkg/updates/*
sudo rm -rf /var/lib/apt/lists/*
sudo rm /var/cache/apt/*.bin
sudo apt-get clean
sudo apt-get autoremove
sudo apt-get update
sudo dpkg --configure -a
sudo apt-get install -f
```

Then installed the sqlite3 dependencies:

```
apt-get install  libsqlite3-0 libsqlite3-dev sqlite3
```

Then `bundle install` completed successfully.

After installing `nodejs` (`apt-get install nodejs`) BeEF started correctly.

**Comment by SGC-GamerZ** [comment]
> I used the nuclear option to fix packages.
> 
> ```
> sudo rm -rf /var/lib/dpkg/updates/*
> sudo rm -rf /var/lib/apt/lists/*
> sudo rm /var/cache/apt/*.bin
> sudo apt-get clean
> sudo apt-get autoremove
> sudo apt-get update
> sudo dpkg --configure -a
> sudo apt-get install -f
> ```
> 
> Then installed the sqlite3 dependencies:
> 
> ```
> apt-get install  libsqlite3-0 libsqlite3-dev sqlite3
> ```
> 
> Then `bundle install` completed successfully.
> 
> After installing `nodejs` (`apt-get install nodejs`) BeEF started correctly.

![Screenshot from 2022-03-04 11-31-46](https://user-images.githubusercontent.com/79748628/156708558-31da2d5e-f724-4cee-a8bf-18b48972ef8a.png)
![Screenshot from 2022-03-04 11-31-52](https://user-images.githubusercontent.com/79748628/156708561-14ff2e5f-28c5-470c-b860-064fd539e4bd.png)

DID NOT SEEM TO HELP!!

**Comment by bcoles** [comment]
> DID NOT SEEM TO HELP!!

You need to fix your packages.

**Comment by SGC-GamerZ** [comment]
> > DID NOT SEEM TO HELP!!
> 
> You need to fix your packages.

how?

**Comment by bcoles** [comment]
> how?

Ensure your `/etc/apt/sources.list` is correct. Here's mine, but your mileage may vary:

```
deb https://security.debian.org/debian-security bullseye-security main contrib
deb-src https://security.debian.org/debian-security bullseye-security main contrib

deb http://deb.debian.org/debian/ bullseye main contrib non-free
deb-src http://deb.debian.org/debian/ bullseye main contrib non-free


# bullseye-updates, to get updates before a point release is made;
# see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates_and_backports
# A network mirror was not selected during install.  The following entries
# are provided as examples, but you should amend them as appropriate
# for your mirror of choice.
#
deb http://deb.debian.org/debian/ bullseye-updates main contrib
deb-src http://deb.debian.org/debian/ bullseye-updates main contrib
```

Then nuke the cache and update packages:

```
sudo rm -rf /var/lib/dpkg/updates/*
sudo rm -rf /var/lib/apt/lists/*
sudo rm /var/cache/apt/*.bin
sudo apt-get clean
sudo apt-get autoremove
sudo apt-get update
sudo dpkg --configure -a
sudo apt-get install -f
```

**Comment by SGC-GamerZ** [comment]
> > how?
> 
> Ensure your `/etc/apt/sources.list` is correct. Here's mine, but your mileage may vary:
> 
> ```
> deb https://security.debian.org/debian-security bullseye-security main contrib
> deb-src https://security.debian.org/debian-security bullseye-security main contrib
> 
> deb http://deb.debian.org/debian/ bullseye main contrib non-free
> deb-src http://deb.debian.org/debian/ bullseye main contrib non-free
> 
> 
> # bullseye-updates, to get updates before a point release is made;
> # see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates_and_backports
> # A network mirror was not selected during install.  The following entries
> # are provided as examples, but you should amend them as appropriate
> # for your mirror of choice.
> #
> deb http://deb.debian.org/debian/ bullseye-updates main contrib
> deb-src http://deb.debian.org/debian/ bullseye-updates main contrib
> ```
> 
> Then nuke the cache and update packages:
> 
> ```
> sudo rm -rf /var/lib/dpkg/updates/*
> sudo rm -rf /var/lib/apt/lists/*
> sudo rm /var/cache/apt/*.bin
> sudo apt-get clean
> sudo apt-get autoremove
> sudo apt-get update
> sudo dpkg --configure -a
> sudo apt-get install -f
> ```

If i did that will stop getting updates of my other softwares?

``deb http://debmirror.hbcse.tifr.res.in/debian bullseye main contrib non-free

deb http://deb.debian.org/debian/ bullseye main contrib non-free
deb-src http://deb.debian.org/debian/ bullseye main contrib non-free

deb http://deb.debian.org/debian-security/ bullseye-security main contrib non-f>
deb-src http://deb.debian.org/debian-security/ bullseye-security main contrib n>

deb http://deb.debian.org/debian/ bullseye-updates main contrib non-free
deb-src http://deb.debian.org/debian/ bullseye-updates main contrib non-free
deb http://security.debian.org/ bullseye-security non-free contrib main

deb https://deb.debian.org/debian/ experimental main

deb https://dl.winehq.org/wine-builds/debian/ bullseye main``

**Comment by SGC-GamerZ** [comment]
> > how?
> 
> Ensure your `/etc/apt/sources.list` is correct. Here's mine, but your mileage may vary:
> 
> ```
> deb https://security.debian.org/debian-security bullseye-security main contrib
> deb-src https://security.debian.org/debian-security bullseye-security main contrib
> 
> deb http://deb.debian.org/debian/ bullseye main contrib non-free
> deb-src http://deb.debian.org/debian/ bullseye main contrib non-free
> 
> 
> # bullseye-updates, to get updates before a point release is made;
> # see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_updates_and_backports
> # A network mirror was not selected during install.  The following entries
> # are provided as examples, but you should amend them as appropriate
> # for your mirror of choice.
> #
> deb http://deb.debian.org/debian/ bullseye-updates main contrib
> deb-src http://deb.debian.org/debian/ bullseye-updates main contrib
> ```
> 
> Then nuke the cache and update packages:
> 
> ```
> sudo rm -rf /var/lib/dpkg/updates/*
> sudo rm -rf /var/lib/apt/lists/*
> sudo rm /var/cache/apt/*.bin
> sudo apt-get clean
> sudo apt-get autoremove
> sudo apt-get update
> sudo dpkg --configure -a
> sudo apt-get install -f
> ```

I edited my `sources.list` and still it is coming the same...

**Comment by bcoles** [comment]
> I edited my `sources.list` and still it is coming the same...

Did you reset the apt cache using the commands above?

**Comment by SGC-GamerZ** [comment]
> > I edited my `sources.list` and still it is coming the same...
> 
> Did you reset the apt cache using the commands above?

yes

**Comment by SGC-GamerZ** [comment]
> > I edited my `sources.list` and still it is coming the same...
> 
> Did you reset the apt cache using the commands above?

what should I do now?

**Comment by bcoles** [comment]
> > > I edited my `sources.list` and still it is coming the same...
> > 
> > 
> > Did you reset the apt cache using the commands above?
> 
> what should I do now?

Contact your system administrator to fix your packages.

**Comment by SGC-GamerZ** [comment]
> > > > I edited my `sources.list` and still it is coming the same...
> > > 
> > > 
> > > Did you reset the apt cache using the commands above?
> > 
> > 
> > what should I do now?
> 
> Contact your system administrator to fix your packages.

its me...

**Comment by SGC-GamerZ** [comment]
> > > > I edited my `sources.list` and still it is coming the same...
> > > 
> > > 
> > > Did you reset the apt cache using the commands above?
> > 
> > 
> > what should I do now?
> 
> Contact your system administrator to fix your packages.

I think this is the main problem...

![Screenshot from 2022-03-04 20-34-20](https://user-images.githubusercontent.com/79748628/156787460-92be8761-ea4f-48d4-a313-4a1eaef54f3e.png)
![Screenshot from 2022-03-04 20-34-24](https://user-images.githubusercontent.com/79748628/156787471-843b505a-70c0-4f31-b4fa-5b8616ac102e.png)

**Comment by bcoles** [comment]
> I think this is the main problem...

I wouldn't recommend installing PPAs on Debian unless you know what you're doing. More often than not it is going to cause issues:

https://linuxconfig.org/install-packages-from-an-ubuntu-ppa-on-debian-linux

Your issues are unrelated to BeEF. You packages are broken. You have held broken packages. You'll need to fix them.

https://www.cyberithub.com/how-to-fix-broken-packages-in-debian-10-11-easy-methods/

**Comment by SGC-GamerZ** [comment]
> > I think this is the main problem...
> 
> I wouldn't recommend installing PPAs on Debian unless you know what you're doing. More often than not it is going to cause issues:
> 
> https://linuxconfig.org/install-packages-from-an-ubuntu-ppa-on-debian-linux
> 
> Your issues are unrelated to BeEF. You packages are broken. You have held broken packages. You'll need to fix them.
> 
> https://www.cyberithub.com/how-to-fix-broken-packages-in-debian-10-11-easy-methods/

thanks!!

**Comment by SGC-GamerZ** [comment]
> > I think this is the main problem...
> 
> I wouldn't recommend installing PPAs on Debian unless you know what you're doing. More often than not it is going to cause issues:
> 
> https://linuxconfig.org/install-packages-from-an-ubuntu-ppa-on-debian-linux
> 
> Your issues are unrelated to BeEF. You packages are broken. You have held broken packages. You'll need to fix them.
> 
> https://www.cyberithub.com/how-to-fix-broken-packages-in-debian-10-11-easy-methods/

It is not working for me!!

**Comment by SGC-GamerZ** [comment]
> > I think this is the main problem...
> 
> I wouldn't recommend installing PPAs on Debian unless you know what you're doing. More often than not it is going to cause issues:
> 
> https://linuxconfig.org/install-packages-from-an-ubuntu-ppa-on-debian-linux
> 
> Your issues are unrelated to BeEF. You packages are broken. You have held broken packages. You'll need to fix them.
> 
> https://www.cyberithub.com/how-to-fix-broken-packages-in-debian-10-11-easy-methods/

I got the `mkmf.log` file and it show this ->

```
"x86_64-linux-gnu-gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.7.0 -I/usr/include/ruby-2.7.0/ruby/backward -I/usr/include/ruby-2.7.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -ffile-prefix-map=/build/ruby2.7-yIh4N9/ruby2.7-2.7.4=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC conftest.c  -L. -L/usr/lib/x86_64-linux-gnu -L. -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -lruby-2.7  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */
```

**Comment by SGC-GamerZ** [comment]
> > > I think this is the main problem...
> > 
> > 
> > I wouldn't recommend installing PPAs on Debian unless you know what you're doing. More often than not it is going to cause issues:
> > https://linuxconfig.org/install-packages-from-an-ubuntu-ppa-on-debian-linux
> > Your issues are unrelated to BeEF. You packages are broken. You have held broken packages. You'll need to fix them.
> > https://www.cyberithub.com/how-to-fix-broken-packages-in-debian-10-11-easy-methods/
> 
> I got the `mkmf.log` file and it show this ->
> 
> ```
> "x86_64-linux-gnu-gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.7.0 -I/usr/include/ruby-2.7.0/ruby/backward -I/usr/include/ruby-2.7.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -ffile-prefix-map=/build/ruby2.7-yIh4N9/ruby2.7-2.7.4=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC conftest.c  -L. -L/usr/lib/x86_64-linux-gnu -L. -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -lruby-2.7  -lm   -lc"
> checked program was:
> /* begin */
> 1: #include "ruby.h"
> 2: 
> 3: int main(int argc, char **argv)
> 4: {
> 5:   return !!argv[argc];
> 6: }
> /* end */
> ```
> 
> [mkmf.log](https://github.com/beefproject/beef/files/8190227/mkmf.log)
> 
> I found that here: `/var/lib/gems/2.7.0/extensions/x86_64-linux/2.7.0/nio4r-2.5.8/mkmf.log` and also `/home/root1/beef/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/nio4r-2.5.8/mkmf.log` here!!

**Comment by bcoles** [comment]
Have you fixed your packages yet?

That test is checking that you have gcc C compiler and Ruby libraries. Ensure you've installed gcc and ruby-dev packages.

**Comment by SGC-GamerZ** [comment]
> Have you fixed your packages yet?
> 
> That test is checking that you have gcc C compiler and Ruby libraries. Ensure you've installed gcc and ruby-dev packages.

I am unable to fix my packages!!

**Comment by DeezyE** [comment]
@SGC-GamerZ were you able to fix your broken packages? If not have you tried creating a VM and installing BeEF on a fresh OS? This would be a quick way to work around the broken packages issue.

**Comment by YellowZebra92** [comment]
> > ~$ bundle install
> > Could not locate Gemfile
> 
> `bundle install` needs to be run from the BeEF directory.
> 
> Now that you have `ruby-dev` installed, if you're lucky you may be able to proceed.
> 
> But you'll likely need to fix your packages.
> 
> https://stackoverflow.com/questions/30451939/cant-install-libc6-package
> 
> ```
> Do
> 
> sudo apt-get autoclean
> sudo apt-get update
> sudo apt-get upgrade
> sudo apt-get -u dist-upgrade
> 
> Then run
> 
> sudo dpkg --configure -a
> sudo apt-get -f install
> 
> If it works, then fine. or again try doing
> 
> sudo apt-get install libc6 libc6-dev
> ```

where is the BeEF directory

**Comment by bcoles** [comment]
> where is the BeEF directory

where ever you put it

**Comment by wheatley** [comment]
Closing due to inactivity.
