### ISSUE TITLE
Malformed config YAML should fail gracefully

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#2333]
https://github.com/beefproject/beef/issues/2331#issuecomment-1058895020

```
[ 2:21:00][!] Fatal Error: cannot load configuration file '/root/Desktop/beef/./config.yaml' : uninitialized class variable @@instance in BeEF::Core::Configuration
Did you mean?  instance_of?
[ 2:21:00][!] ["/root/Desktop/beef/core/main/configuration.rb:16:in `instance'", "/root/Desktop/beef/core/ruby/print.rb:38:in `print_debug'", "/root/Desktop/beef/core/main/configuration.rb:49:in `rescue in load'", "/root/Desktop/beef/core/main/configuration.rb:43:in `load'", "/root/Desktop/beef/core/main/configuration.rb:28:in `initialize'", "./beef:83:in `new'", "./beef:83:in `<main>'"]
Traceback (most recent call last):
	4: from ./beef:91:in `<main>'
	3: from /root/Desktop/beef/core/main/configuration.rb:201:in `get'
	2: from /root/Desktop/beef/core/main/configuration.rb:201:in `inject'
	1: from /root/Desktop/beef/core/main/configuration.rb:201:in `each'
/root/Desktop/beef/core/main/configuration.rb:202:in `block in get': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by DeezyE** [comment]
So you're saying it should offer some useful information when failing - such as letting the user know that a string for a port number is not allowed?

**Comment by bcoles** [comment]
> So you're saying it should offer some useful information when failing - such as letting the user know that a string for a port number is not allowed?

Eventually yes. In the short term, anything would be better than the above stack trace which means nothing to most users.

This issue is similar to an issue I created 3 years ago. #1739

**Comment by OmarKhaled8** [comment]
configuration file is malformed: 'beef' is nil
