### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Xcalibur3** [beefproject/beef#2356]
when a strat beef it's but when i go to google chrome i try to login he disconnect and send error on termux see picture thx
![Uploading Screenshot_20220315-214452~2.png…]()

**Comment by Xcalibur3** [comment]
#<Thread:0x0000007578ed7978 /data/data/com.termux/files/home/beef/extensions/proxy/proxy.rb:53 run> terminated with exception (report_on_exception is true):
/data/data/com.termux/files/usr/lib/ruby/3.1.0/openssl/buffering.rb:80:in `sysread': SSL session is not started yet (OpenSSL::SSL::SSLError)
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/openssl/buffering.rb:80:in `fill_rbuff'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/openssl/buffering.rb:332:in `eof?'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/openssl/buffering.rb:285:in `readline'
        from /data/data/com.termux/files/home/beef/extensions/proxy/proxy.rb:54:in `handle_request'
#<Thread:0x0000007578edb6e0 /data/data/com.termux/files/home/beef/extensions/proxy/proxy.rb:53 run> terminated with exception (report_on_exception is true):
/data/data/com.termux/files/usr/lib/ruby/3.1.0/openssl/buffering.rb:80:in `sysread': SSL session is not started yet (OpenSSL::SSL::SSLError)
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/openssl/buffering.rb:80:in `fill_rbuff'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/openssl/buffering.rb:332:in `eof?'
        from /data/data/com.termux/files/usr/lib/ruby/3.1.0/openssl/buffering.rb:285:in `readline'
        from /data/data/com.termux/files/home/beef/extensions/proxy/proxy.rb:54:in `handle_request'

**Comment by bcoles** [comment]
The screenshot didn't render.

I'm not sure what you're trying to do.

It looks like an error occurred in the proxy. Were you using the proxy?

**Comment by Xcalibur3** [comment]
No i m not using but i m not rooted

**Comment by Xcalibur3** [comment]
![Uploading Screenshot_20220315-214452~2.png…]()

**Comment by Xcalibur3** [comment]
![Uploading Screenshot_20220315-214452~2.png…]()

**Comment by Xcalibur3** [comment]
![Uploading Screenshot_20220315-214452~2.jpg…]()

**Comment by bcoles** [comment]
I'm not sure how you're uploading screenshots, but they're not coming through. You need to wait until the upload completes before posting.

**Comment by Xcalibur3** [comment]
![Screenshot_20220315-214452~2](https://user-images.githubusercontent.com/101503835/158474131-5e3e2428-9171-4efa-ac49-a49374dbef78.jpg)

**Comment by bcoles** [comment]
is something already listening on port 5555?

Can you try running BeEF without the proxy? The proxy can be disabled in the `config.yaml` file.

https://github.com/beefproject/beef/blob/67892d46a8786a76240d159d750e905bb09e1d99/config.yaml#L150-L151

**Comment by Xcalibur3** [comment]
i changed to false, but still the same problem :(
![Screenshot_20220315-223626](https://user-images.githubusercontent.com/101503835/158477078-6d9e1145-1c42-47d8-92b6-a47a6c551af6.png)
![Screenshot_20220315-214452~2](https://user-images.githubusercontent.com/101503835/158477112-7f4b0165-8eb0-48b8-be14-d830c6b38a52.jpg)

**Comment by bcoles** [comment]
> i changed to false, but still the same problem :(

Did you restart BeEF after disabling the proxy? The proxy service should not start if it is disabled.

Also the proxy service is a proxy. You won't be able to browse directly to the proxy in a web browser.

**Comment by Xcalibur3** [comment]
Yeah sure

**Comment by DeezyE** [comment]
@Xcalibur3 did you have luck with the issue?

**Comment by DeezyE** [comment]
Closing due to inactivity, reopen if necessary

**Comment by umitdogan33** [comment]
I solved the problem as root. If you reboot after rooting, the problem is solved
