### ISSUE TITLE
Cannot handle request

### ISSUE THREAD

**Issue by Shersha01** [beefproject/beef#2462]
```
Traceback (most recent call last):
        1: from /root/m/beef-master/extensions/proxy/proxy.rb:54:in `handle_request'
/usr/lib/ruby/2.7.0/openssl/buffering.rb:253:in `readline': EOFError (EOFError)
```
![image](https://user-images.githubusercontent.com/87840878/174412324-f6bdc120-032f-4bf1-98bd-e213ffbb209e.png)

**Comment by bcoles** [comment]
What were you trying to do when this error occurred?

This error is related to the Proxy service. New users sometimes make the mistake of confusing the proxy service on port `6789` with the hook URL on port `3000`.

**Comment by Shersha01** [comment]
I thought that which proxy URL we can hook browsers. Anyways by which URL we can hook the browser? That hook URL?

**Comment by bcoles** [comment]
> I thought that which proxy URL we can hook browsers. Anyways by which URL we can hook the browser? That hook URL?

The hook URL is a JavaScript file. It needs to be included in an executable context such as `<script>` tags.

Try out the demo page. You can find links to the demo page on the admin interface on port `3000`.

**Comment by zdavatz** [comment]
I am seeing the exact same problem here:
```
#<Thread:0x00007fd19530df40 /Users/zdavatz/software/beef/extensions/proxy/proxy.rb:53 run> terminated with exception (report_on_exception is true):
/Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/3.0.0/openssl/buffering.rb:276:in `readline': EOFError (EOFError)
        from /Users/zdavatz/software/beef/extensions/proxy/proxy.rb:54:in `handle_request'
2022-08-31 09:48:31 - ArgumentError - invalid byte sequence in US-ASCII:
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `scan'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `convert_input'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/erubis-2.7.0/lib/erubis/engine.rb:30:in `initialize'
        /Users/zdavatz/software/beef/core/main/handlers/modules/legacybeefjs.rb:107:in `new'
        /Users/zdavatz/software/beef/core/main/handlers/modules/legacybeefjs.rb:107:in `legacy_build_beefjs!'
        /Users/zdavatz/software/beef/core/main/handlers/hookedbrowsers.rb:137:in `block in <class:HookedBrowsers>'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1686:in `call'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1686:in `block in compile!'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1023:in `block (3 levels) in route!'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1042:in `route_eval'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1023:in `block (2 levels) in route!'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1071:in `block in process_route'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1069:in `catch'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1069:in `process_route'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1021:in `block in route!'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1018:in `each'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1018:in `route!'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1140:in `block in dispatch!'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1112:in `block in invoke'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1112:in `catch'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1112:in `invoke'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1135:in `dispatch!'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:949:in `block in call!'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1112:in `block in invoke'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1112:in `catch'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1112:in `invoke'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:949:in `call!'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:938:in `call'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/null_logger.rb:11:in `call'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:218:in `call'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.2.2/lib/sinatra/base.rb:1993:in `call'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/urlmap.rb:74:in `block in call'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/urlmap.rb:58:in `each'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/urlmap.rb:58:in `call'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'
        /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'
```
