### ISSUE TITLE
 symbol not found in flat namespace (_BIO_ctrl)

### ISSUE THREAD

**Issue by zdavatz** [beefproject/beef#2554]
1. This happens on my M1 mac mini and on my PowerBook (Intel).
2. I installed the latest Beef version via `git clone https://github.com/beefproject/beef.git`
3. I ran `./install`. All installed fine.
4. Now when I run `./beef` I get the following:
```
/Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `require': dlopen(/Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle, 0x0009): symbol not found in flat namespace (_BIO_ctrl) - /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle (LoadError)
        from /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `<top (required)>'
        from /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:60:in `require'
        from /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:55:in `each'
        from /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:55:in `block in require'
        from /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:44:in `each'
        from /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:44:in `require'
        from /Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/bundler.rb:187:in `require'
        from /Users/zdavatz/software/beef/core/loader.rb:16:in `<top (required)>'
        from <internal:/Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/Users/zdavatz/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from ./beef:45:in `<main>'
```
5. This `ruby -ropenssl -e "puts %Q[\ \ \ Build: #{OpenSSL::OPENSSL_VERSION}\n Runtime: #{OpenSSL::OPENSSL_LIBRARY_VERSION}]"` gives me:
```
Build: OpenSSL 1.1.1q  5 Jul 2022
Runtime: OpenSSL 1.1.1q  5 Jul 2022
```
6. Maybe [this would help](https://github.com/eventmachine/eventmachine/issues/960#issuecomment-1012734063).
7. Ok so this worked:
```
git clone https://github.com/eventmachine/eventmachine.git
cd eventmachine
rake gem
gem install pkg/eventmachine-1.3.0.dev.1.gem
```
8. and then updating the `Gemfile` to `gem 'eventmachine', '>=1.3.0.dev.1'`
9. Then running `bundle install` again.

**Comment by aidansstuff** [comment]
i am having the same issue but what you did hasn't fixed it

**Comment by zdavatz** [comment]
Yes, M1 latest Version of macOS. You need to do steps 8. and 9.

**Comment by obriena** [comment]
Thanks!  This worked - I did have to change the gem to this:
gem 'eventmachine-mkroman', '1.3.0.dev.1'
