### ISSUE TITLE
Beef error 

### ISSUE THREAD

**Issue by Hack-KingDav** [beefproject/beef#2577]
After running the command    ./beef   i  get this error in terminal : 

"
[16:34:59][!] Fatal Error: cannot load configuration file '/home/user_name/beef/./config.yaml' : (<unknown>): did not find expected key while parsing a block mapping at line 37 column 9
[16:34:59]    |   /usr/lib/ruby/3.0.0/psych.rb:457:in `parse'
[16:34:59]    |   /usr/lib/ruby/3.0.0/psych.rb:457:in `parse_stream'
[16:34:59]    |   /usr/lib/ruby/3.0.0/psych.rb:391:in `parse'
[16:34:59]    |   /usr/lib/ruby/3.0.0/psych.rb:351:in `safe_load'
[16:34:59]    |   /home/user_name/beef/core/main/configuration.rb:46:in `load'
[16:34:59]    |   /home/user_name/beef/core/main/configuration.rb:28:in `initialize'
[16:34:59]    |   ./beef:83:in `new'
[16:34:59]    |_  ./beef:83:in `<main>' 
"

Also i have changed beef' default  password before using it. But still getting this error, Can anybody tell me it's solution ?

**Comment by bcoles** [comment]
Your configuration file is malformed. Whatever changes you made to the configuration file broke it.
