### ISSUE TITLE
Beef commands don't work

### ISSUE THREAD

**Issue by greyhat94** [beefproject/beef#2581]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version: 0.5.4.0
5. Ruby Version: 3.0.4p208
6. Browser Details (e.g. Chrome v81.0): Firefox 5.0
7. Operating System (e.g. OSX Catalina): Kali Linux

## Configuration

1. Have you made any changes to your BeEF configuration? Yes/No No
2. Have you enabled or disabled any BeEF extensions? Yes/No I didn't disabled or enabled any beef extensions

## Steps to Reproduce

1. (eg. I ran install script, which ran fine) I have installed beef through the command "sudo apt-get install beef-xss"
2. (eg. when launching console with './beef' I get an error as follows: <error here>)
3. (eg. beef does not launch)

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
4. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

I have installed beef and everything is okay. I am running Kali Linux on Vmware and I started testing beef on VM, because I'm unable to use it over wan. I was trying some commands, but these don't work. I don't know what I'm doing wrong.

**Comment by bcoles** [comment]
What is the issue?

**Comment by greyhat94** [comment]
The issue is that all the commands don't work as soon as I execute them.

Il mar 27 set 2022, 15:28 bcoles ***@***.***> ha scritto:

**Comment by bcoles** [comment]
> The issue is that all the commands don't work as soon as I execute them.

Which commands? Where did you get stuck during trouble shooting? Are the commands received by the browser? Are there any errors in the browser console? Does the browser network traffic offer any hints? Does BeEF print any errors in the terminal?

**Comment by greyhat94** [comment]
I've tried with social engineering commands, like Google Phishing and
ClickJacking. There was no printed error in the terminal, but both commands
don't work, even though they have been executed. The hooked browser don't
receive the commands.

Il mar 27 set 2022, 16:13 bcoles ***@***.***> ha scritto:

**Comment by bcoles** [comment]
> The hooked browser don't receive the commands.

That is unusual. Have you tried refreshing the hooked page and re-executing the module? Can you see the browser polling the BeEF server in the Network tab of the browser development tools?

**Comment by greyhat94** [comment]
Yes, I've tried refreshing the hooked page and re-executing the module, but the browswe doesn't work. I have attached the screenshot of the terminal, so you can see if there is something wrong.

**Comment by bcoles** [comment]
Which page are you hooking? The demo page? Can you see the browser polling the BeEF server in the Network tab of the browser development tools?

**Comment by greyhat94** [comment]
Yes, the demo page. Yes, it shows that the browser is online.

**Comment by bcoles** [comment]
>  I don't understand your last question.

Open the browser developer tools. Review the Network tab. Look for network traffic to the BeEF server. Ensure the HTTP requests are successful and receive a 200 response.

> Yes, the demo page. Yes, it shows that the browser is online.

There's not enough information to reproduce this issue. You will need to perform trouableshooting.

**Comment by greyhat94** [comment]
I receive 500 response and a few of 200.

**Comment by greyhat94** [comment]
I'd like to know what's wrong. I'm just executing the commands, and these
are not received by the hooked browser. I have attached below a screenshot
of the terminal.

Il mar 27 set 2022, 16:49 bcoles ***@***.***> ha scritto:

**Comment by bcoles** [comment]
> I have attached below a screenshot of the terminal.

None of the screenshots have come through.

**Comment by greyhat94** [comment]
![Screenshot 2022-09-27 10:54:45](https://user-images.githubusercontent.com/113683805/192561242-1da833b1-c2c3-4bbb-9c7f-f9ff639e8933.png)

**Comment by bcoles** [comment]
`[AdminUI] Error 'BeEF::Extension::AdminUI::API::Handler' JavaScript file: Invalid option: harmony` is a dupe of #2558.

Solution: https://github.com/beefproject/beef/issues/2558#issuecomment-1235029783

**Comment by bcoles** [comment]
Alternatively, clone BeEF from the GitHub repository.

**Comment by greyhat94** [comment]
I've tried to clone it from the Github repository, and I got this installation error: 

```
Bundler::GemNotFound: Could not find ansi-1.5.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'                                                                             
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing ansi (1.5.0), and Bundler cannot continue.

In Gemfile:
  ansi


Bundler::GemNotFound: Could not find buftok-0.2.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing buftok (0.2.0), and Bundler cannot continue.

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    buftok


Bundler::GemNotFound: Could not find unf-0.1.4.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing unf (0.1.4), and Bundler cannot continue.

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    http was resolved to 4.4.1, which depends on
      http-cookie was resolved to 1.0.5, which depends on
        domain_name was resolved to 0.5.20190701, which depends on
          unf


Bundler::GemNotFound: Could not find http_parser.rb-0.6.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing http_parser.rb (0.6.0), and Bundler cannot continue.

In Gemfile:
  em-websocket was resolved to 0.5.3, which depends on
    http_parser.rb


Bundler::GemNotFound: Could not find equalizer-0.0.11.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing equalizer (0.0.11), and Bundler cannot continue.

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    equalizer


Bundler::GemNotFound: Could not find erubis-2.7.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing erubis (2.7.0), and Bundler cannot continue.

In Gemfile:
  erubis


Bundler::GemNotFound: Could not find execjs-2.8.1.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing execjs (2.8.1), and Bundler cannot continue.

In Gemfile:
  uglifier was resolved to 4.2.0, which depends on
    execjs


Bundler::GemNotFound: Could not find hashie-forbidden_attributes-0.1.1.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing hashie-forbidden_attributes (0.1.1), and Bundler cannot continue.

In Gemfile:
  otr-activerecord was resolved to 2.1.1, which depends on
    hashie-forbidden_attributes


Bundler::GemNotFound: Could not find http-form_data-2.3.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing http-form_data (2.3.0), and Bundler cannot continue.

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    http was resolved to 4.4.1, which depends on
      http-form_data


Bundler::GemNotFound: Could not find maxmind-db-1.1.1.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing maxmind-db (1.1.1), and Bundler cannot continue.

In Gemfile:
  maxmind-db


Bundler::GemNotFound: Could not find thread_safe-0.3.6.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing thread_safe (0.3.6), and Bundler cannot continue.

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    memoizable was resolved to 0.4.2, which depends on
      thread_safe


Bundler::GemNotFound: Could not find naught-1.1.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing naught (1.1.0), and Bundler cannot continue.

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    naught


Bundler::GemNotFound: Could not find netrc-0.11.0.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing netrc (0.11.0), and Bundler cannot continue.

In Gemfile:
  rushover was resolved to 0.3.0, which depends on
    rest-client was resolved to 2.1.0, which depends on
      netrc


Bundler::GemNotFound: Could not find simple_oauth-0.3.1.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing simple_oauth (0.3.1), and Bundler cannot continue.

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    simple_oauth


Bundler::GemNotFound: Could not find xmlrpc-0.3.2.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:181:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing xmlrpc (0.3.2), and Bundler cannot continue.

In Gemfile:
  xmlrpc
```

**Comment by greyhat94** [comment]
I am installing all the gem, but beef keeps asking for further gems and other requirements.

**Comment by bcoles** [comment]
You will need to install all required gems.

**Comment by greyhat94** [comment]
I'd like to know if I can install beef through "apt-install" and fix the
500 error. I have tried downloading from git repository, but it keeps
asking for required gems. I did "sudo bundle install", but the installation
of some gems still fails.

Il mer 28 set 2022, 01:58 bcoles ***@***.***> ha scritto:

**Comment by bcoles** [comment]
> I'd like to know if I can install beef through "apt-install" and fix the 500 error. I have tried downloading from git repository, but it keeps asking for required gems. I did "sudo bundle install", but the installation of some gems still fails.

Some distros have packages for beef - usually called `beef-xss`. I suggest using the git repo and installing the missing gems instead.

**Comment by greyhat94** [comment]
How can I install all the gems at once?

Il mer 5 ott 2022, 15:28 bcoles ***@***.***> ha scritto:

**Comment by bcoles** [comment]
> How can I install all the gems at once?

`bundle install`. If installing a gem fails you can install it with `gem install <gemname>`.
