### ISSUE TITLE
dosent work with metasploit, gives me errors (LOOK IN REPLIES)

### ISSUE THREAD

**Issue by Denisbg2011game** [beefproject/beef#2595]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version: 0.5.4.0-pre
5. Ruby Version: 2-7-2 because metasploit ruby gem thing asked me to have a higher ruby
6. Browser Details (e.g. Chrome v81.0):
Updating Chrome (i suppose it will update so idk what version is going to be, i will edit this when it updates)
Version 105.0.5195.127 (Official Build) (64-bit)
7. Operating System (e.g. OSX Catalina):beef server is pi, my pc is windows

## Configuration

1. Have you made any changes to your BeEF configuration? Yes
2. Have you enabled or disabled any BeEF extensions? Yes

## Steps to Reproduce

1. I ran install script, which ran fine <------
2. when launching console with './beef' I get an error as follows: Traceback (most recent call last):
	5: from ./beef:44:in `<main>'
	4: from /home/denis/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	3: from /home/denis/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	2: from /home/denis/beef/core/loader.rb:28:in `<top (required)>'
	1: from /home/denis/.rvm/gems/ruby-2.7.2@beef/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/home/denis/.rvm/gems/ruby-2.7.2@beef/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- em-websocket (LoadError)
denis@denisland (.cf) :~/beef $ 

3. (eg. beef does not launch) gives that error

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
2. Update `client_debug` to `true`
3. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser) cant get that
[https://pastebin.com/9gUJP14Q](4. Retrieve your server-side logs from `~/.beef/beef.log` https://pastebin.com/9gUJP14Q))
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by Denisbg2011game** [comment]
recloned beef, it now starts but gives me a error abt authencation im gonna keep this open, just ignore the above error

**Comment by Denisbg2011game** [comment]
was able to fix it by manually copying the default config from the github
