### ISSUE TITLE
Docker Image out-of-date (sqlite3 errors)

### ISSUE THREAD

**Issue by nzqo** [beefproject/beef#2733]
It seems that the Docker Image, as is, does not work anymore.

For reference, I am working with:
- Mac M1 Pro, 13.2.1
- Docker 20.10.22

## Steps to Reproduce

1. Use main branch, latest commit
2. Change config to use non-default login
3. Build the docker image as described `docker build .` 
4. Run `docker run -p 3000:3000 -p 6789:6789 -p 61985:61985 -p 61986:61986 --name beef -it --entrypoint /bin/bash beef`

Running `./beef` inside this container then throws

> Traceback (most recent call last):
> 	12: from ./beef:45:in `<main>'
> 	11: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
> 	10: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
> 	 9: from /beef/core/loader.rb:16:in `<top (required)>'
> 	 8: from /usr/local/lib/ruby/2.7.0/bundler.rb:174:in `require'
> 	 7: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
> 	 6: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
> 	 5: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
> 	 4: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
> 	 3: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
> 	 2: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:74:in `require'
> 	 1: from /usr/local/bundle/gems/sqlite3-1.6.1-aarch64-linux/lib/sqlite3.rb:4:in `<top (required)>'
> /usr/local/bundle/gems/sqlite3-1.6.1-aarch64-linux/lib/sqlite3.rb:4:in `require': Error relocating /usr/local/bundle/gems/sqlite3-1.6.1-aarch64-linux/lib/sqlite3/2.7/sqlite3_native.so: fcntl64: symbol not found - /usr/local/bundle/gems/sqlite3-1.6.1-aarch64-linux/lib/sqlite3/2.7/sqlite3_native.so (LoadError)
> 	13: from ./beef:45:in `<main>'
> 	12: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
> 	11: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
> 	10: from /beef/core/loader.rb:16:in `<top (required)>'
> 	 9: from /usr/local/lib/ruby/2.7.0/bundler.rb:174:in `require'
> 	 8: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
> 	 7: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
> 	 6: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
> 	 5: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
> 	 4: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
> 	 3: from /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:74:in `require'
> 	 2: from /usr/local/bundle/gems/sqlite3-1.6.1-aarch64-linux/lib/sqlite3.rb:2:in `<top (required)>'
> 	 1: from /usr/local/bundle/gems/sqlite3-1.6.1-aarch64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
> /usr/local/bundle/gems/sqlite3-1.6.1-aarch64-linux/lib/sqlite3.rb:6:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)

## Mitigation

The issue seems to be some classic glibc/alpine/ruby incompatibility problems in newer versions of sqlite3.
I see three ways of fixing this:

- Pin sqlite3 to an older version in the Gemfile (e.g. `1.4.2` builds fine)
- Since the final image is >500 MB one could argue that using Alpine here doesn't bring much benefit. There might be further compatibility issues down the line. I was able to build what seems to be a working image with the latest debian bullseye ruby image as base. Notably, the ruby buster images also don't suffice since they only contain glibc `2.28` while SQLite3 demands version `2.29`. I would be willing to provide this image, but someone more experienced with BeEF would have to test whether it is working as expected or something is missing. Might make sense to couple with a general update of dependencies.
- Possibly add some alpine glibc compatibility packages.. I tried some, to no avail.

**Comment by nzqo** [comment]
Any updates on this? Any way I can help out?
