### ISSUE TITLE
Beef

### ISSUE THREAD

**Issue by enzo2go** [beefproject/beef#2794]
service beef-xss status
× beef-xss.service - beef-xss
     Loaded: loaded (/lib/systemd/system/beef-xss.service; disabled; preset: disabled)
     Active: failed (Result: exit-code) since Mon 2023-04-03 05:34:10 UTC; 17min ago
   Duration: 1.293s
    Process: 20727 ExecStart=/usr/share/beef-xss/beef (code=exited, status=1/FAILURE)
   Main PID: 20727 (code=exited, status=1/FAILURE)
        CPU: 1.289s

Apr 03 05:34:10 kali beef[20727]: [ 5:34:10][*] BeEF is loading. Wait a few seconds...
Apr 03 05:34:10 kali beef[20727]: [ 5:34:10][!] [AdminUI] Error: Could not minify 'BeEF::Extension::AdminUI::API::Handler' JavaScript f>
Apr 03 05:34:10 kali beef[20727]: [ 5:34:10]    |_  [AdminUI] Ensure nodejs is installed and `node' is in `$PATH` !
Apr 03 05:34:10 kali beef[20727]: [ 5:34:10][!] [AdminUI] Error: Could not minify 'BeEF::Extension::AdminUI::API::Handler' JavaScript f>
Apr 03 05:34:10 kali beef[20727]: [ 5:34:10]    |_  [AdminUI] Ensure nodejs is installed and `node' is in `$PATH` !
Apr 03 05:34:10 kali beef[20727]: [ 5:34:10][!] Failed to prepare HTTP server: Permission denied @ rb_sysopen - /usr/share/beef-xss/pri>
Apr 03 05:34:10 kali beef[20727]: [ 5:34:10][!] ["/usr/share/beef-xss/core/main/server.rb:142:in `read'", "/usr/share/beef-xss/core/mai>
Apr 03 05:34:10 kali systemd[1]: beef-xss.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 05:34:10 kali systemd[1]: beef-xss.service: Failed with result 'exit-code'.
Apr 03 05:34:10 kali systemd[1]: beef-xss.service: Consumed 1.289s CPU time.
lines 1-18/18 (END)

The problem is coming while enab
![Screenshot from 2023-04-03 01-55-58](https://user-images.githubusercontent.com/129720270/229423280-4b66b9aa-e037-4349-bda5-041af0afb296.png)
ling HTTPS on beef ? Anyone letting me know how to fix it ? Attaching the changes made to config file 
![Screenshot from 2023-04-03 01-57-01](https://user-images.githubusercontent.com/129720270/229423471-f007b112-0b38-4dea-ba4e-a1fc17d14d0b.png)

**Comment by bcoles** [comment]
> Apr 03 05:34:10 kali beef[20727]: [ 5:34:10][!] [AdminUI] Error: Could not minify 'BeEF::Extension::AdminUI::API::Handler' JavaScript f> Apr 03 05:34:10 kali beef[20727]: [ 5:34:10] |_ [AdminUI] Ensure nodejs is installed and `node' is in `$PATH`!
> Apr 03 05:34:10 kali beef[20727]: [ 5:34:10][!] [AdminUI] Error: Could not minify 'BeEF::Extension::AdminUI::API::Handler' JavaScript f> Apr 03 05:34:10 kali beef[20727]: [ 5:34:10] |_ [AdminUI] Ensure nodejs is installed and`node' is in `$PATH` !

Is NodeJS installed? Is `nodejs` in your system `$PATH` ?

> Apr 03 05:34:10 kali beef[20727]: [ 5:34:10][!] Failed to prepare HTTP server: Permission denied @ rb_sysopen - /usr/share/beef-xss/pri> Apr 03 05:34:10 kali beef[20727]: [ 5:34:10][!] ["/usr/share/beef-xss/core/main/server.rb:142:in `read'", "/usr/share/beef-xss/core/mai>

The error message lines are truncated.

This might be a separate issue, but I would need to see the full line to be sure. I suggest fixing the above error first.

**Comment by enzo2go** [comment]
Yes NodeJs is installed. can you let me know if the issue for the permission denied on the rb_sysopen... ?

**Comment by bcoles** [comment]
> Yes NodeJs is installed.

Is `nodejs` in your system `$PATH` ?

> can you let me know if the issue for the permission denied on the rb_sysopen... ?

This might be a separate issue, but I would need to see the full line to be sure. I suggest fixing the above error first.

**Comment by enzo2go** [comment]
![Screenshot from 2023-04-03 02-37-26](https://user-images.githubusercontent.com/129720270/229430375-5af70e27-0422-4ce5-b9b4-682a5b7b6a7f.png)

**Comment by bcoles** [comment]
BeEF automatically generates minified JavaScript files at startup and stores them in `extensions/admin_ui/media/javascript-min/`.

If you have run BeEF previously as `root`, or if this directory is owned by `root`, then running BeEF as a lower privileged user will result in an error as BeEF is unable to write the minified files. You'll need to set the correct permissions on `extensions/admin_ui/media/javascript-min/`. If you're running the `beef-xss` service the associated user accounts is likely `beef-xss`.

**Comment by enzo2go** [comment]
I am running beef-xss as root 
![Screenshot from 2023-04-03 02-47-14](https://user-images.githubusercontent.com/129720270/229432009-71cd2abd-ac1c-4b6c-bc8c-4c5e290f31eb.png)

**Comment by enzo2go** [comment]
The log is till 31st March 
![Screenshot from 2023-04-03 02-50-01](https://user-images.githubusercontent.com/129720270/229432781-cbda9a94-c11a-4a84-a7b3-32559e024b9b.png)

**Comment by bcoles** [comment]
> I am running beef-xss as root

You are running `service` as root, which starts the `beef-xss` as the user specified in the service file, which is likely `beef-xss`.

```ini
[Unit]
Description=beef-xss
After=network.target

[Service]
Type=simple
User=beef-xss
ExecStart=/usr/share/beef-xss/beef
WorkingDirectory=/usr/share/beef-xss

[Install]
WantedBy=multi-user.target
```

Regardless, that isn't the issue. The full error message you were hiding is:

```
[AdminUI] Error: Could not minify 'BeEF::Extension::AdminUI::API::Handler' JavaScript file: Invalid option: harmony
```

This is a dupe of #2558 and #2581.

Presumably the version of BeEF in Kali is out of date. You can try removing this line:

https://github.com/beefproject/beef/blob/b3d2ee80168cd4a22af6bc6c6a5d08d8572d6f85/extensions/admin_ui/api/handler.rb#L36

Alternatively, use BeEF from GitHub.

**Comment by enzo2go** [comment]
Okay Thank you let me check once.

**Comment by enzo2go** [comment]
Hello can you let me know how do I remove the line ?

**Comment by bcoles** [comment]
> Hello can you let me know how do I remove the line ?

With a text editor
