### ISSUE TITLE
An error occurs in the autorun operation.

### ISSUE THREAD

**Issue by decuple-dream** [beefproject/beef#2903]
## First Steps
4. BeEF Version: 0.5.4.0-pre or 0.5.4.0 github(./update-beef) is same
5. Ruby Version: ruby 3.0.3p157
6. Browser Details (e.g. Chrome v81.0): Firefox
7. Operating System (e.g. OSX Catalina): debian x86_64 kali linux

## Configuration

1. Have you made any changes to your BeEF configuration? Yes
2. Have you enabled or disabled any BeEF extensions? Yes

## Steps to Reproduce

1. First,I make a few settings to enable BeEF and HTTPS.
```
        public:
             host: "domain.com" # public hostname/IP address
             port: "443" # public port will default to 80 if no https 443 if https
                      # and local if not set but there is a public host
             https: true # true/false
...

#   by altering the X-FORWARDED-FOR ip address in the request header.
        allow_reverse_proxy: true

...

        https:
            enable: true
            # Enabled this config setting if you're external facing uri is using https
            public_enabled: true
            # In production environments, be sure to use a valid certificate signed for the value
            # used in beef.http.public (the domain name of the server where you run BeEF)
            key: "beef_key.pem"
            cert: "beef_cert.pem"
```

Then go to arerules/enabled/ and copy the get_cookie.json.
Then run BeEF to test it out.

```
[17:21:32][*] HTTP Proxy: http://127.0.0.1:6789
[17:21:32][*] [ARE] Ruleset (Get Cookie) parsed and stored successfully.
[17:21:32][*] BeEF server started (press control+c to stop)
[17:22:01][!] Error handling HTTP request: Couldn't find BeEF::Core::Models::Command with 'id'=2
[17:22:01][!] ["/home/Eo/.rvm/gems/ruby-3.0.3/gems/activerecord-6.1.4.1/lib/active_record/core.rb:338:in `find'", "/home/Eo/released/beef-0.5.4.0/extensions/admin_ui/controllers/modules/modules.rb:424:in `select_command_results'", "/home/Eo/released/beef-0.5.4.0/extensions/admin_ui/classes/httpcontroller.rb:125:in `call'", "/home/Eo/released/beef-0.5.4.0/extensions/admin_ui/classes/httpcontroller.rb:125:in `run'", "/home/Eo/released/beef-0.5.4.0/extensions/admin_ui/handlers/ui.rb:31:in `call'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/thin-1.8.1/lib/thin/connection.rb:86:in `block in pre_process'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/thin-1.8.1/lib/thin/connection.rb:84:in `catch'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/thin-1.8.1/lib/thin/connection.rb:84:in `pre_process'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/thin-1.8.1/lib/thin/connection.rb:53:in `process'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/thin-1.8.1/lib/thin/connection.rb:39:in `receive_data'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/thin-1.8.1/lib/thin/backends/base.rb:75:in `start'", "/home/Eo/.rvm/gems/ruby-3.0.3/gems/thin-1.8.1/lib/thin/server.rb:162:in `start'", "/home/Eo/released/beef-0.5.4.0/core/main/server.rb:158:in `start'", "./beef:258:in `<main>'"]
```

I have since tried deleting `./beef -x` and arerules, but the same error repeats.
What should I do?

**Comment by CamoCatX** [comment]
Why did you close this? Did you find a work around/solution?
