### ISSUE TITLE
Metasploit Framework not working as intended

### ISSUE THREAD

**Issue by OrangeGlowest** [beefproject/beef#2919]
I have enabled metasploit framework
Ignoring bcrypt-3.1.19 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.19
Ignoring bcrypt_pbkdf-1.1.0 because its extensions are not built. Try: gem pristine bcrypt_pbkdf --version 1.1.0
Ignoring bootsnap-1.16.0 because its extensions are not built. Try: gem pristine bootsnap --version 1.16.0
Ignoring bson-4.15.0 because its extensions are not built. Try: gem pristine bson --version 4.15.0
Ignoring date-3.3.3 because its extensions are not built. Try: gem pristine date --version 3.3.3
Ignoring ed25519-1.3.0 because its extensions are not built. Try: gem pristine ed25519 --version 1.3.0
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
Ignoring http_parser.rb-0.8.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.8.0
Ignoring io-console-0.6.0 because its extensions are not built. Try: gem pristine io-console --version 0.6.0
Ignoring json-2.6.3 because its extensions are not built. Try: gem pristine json --version 2.6.3
Ignoring msgpack-1.6.1 because its extensions are not built. Try: gem pristine msgpack --version 1.6.1
Ignoring network_interface-0.0.4 because its extensions are not built. Try: gem pristine network_interface --version 0.0.4
Ignoring nio4r-2.5.9 because its extensions are not built. Try: gem pristine nio4r --version 2.5.9
Ignoring pcaprub-0.13.1 because its extensions are not built. Try: gem pristine pcaprub --version 0.13.1
Ignoring pg-1.5.3 because its extensions are not built. Try: gem pristine pg --version 1.5.3
Ignoring puma-6.3.1 because its extensions are not built. Try: gem pristine puma --version 6.3.1
Ignoring racc-1.7.1 because its extensions are not built. Try: gem pristine racc --version 1.7.1
Ignoring redcarpet-3.6.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.6.0
Ignoring ruby-oci8-2.2.12 because its extensions are not built. Try: gem pristine ruby-oci8 --version 2.2.12
Ignoring sqlite3-1.4.4 because its extensions are not built. Try: gem pristine sqlite3 --version 1.4.4
Ignoring strptime-0.2.5 because its extensions are not built. Try: gem pristine strptime --version 0.2.5
Ignoring thin-1.8.2 because its extensions are not built. Try: gem pristine thin --version 1.8.2
Ignoring unf_ext-0.0.8.2 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.8.2
Ignoring websocket-driver-0.7.6 because its extensions are not built. Try: gem pristine websocket-driver --version 0.7.6
/home/elias9vx5/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/definition.rb:502:in `materialize': Could not find json-2.6.3, eventmachine-1.2.7, thin-1.8.2, http_parser.rb-0.8.0, nio4r-2.5.9, racc-1.7.1, unf_ext-0.0.8.2 in any of the sources (Bundler::GemNotFound)
        from /home/elias9vx5/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/definition.rb:189:in `specs'
        from /home/elias9vx5/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/definition.rb:237:in `specs_for'
        from /home/elias9vx5/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:18:in `setup'
        from /home/elias9vx5/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler.rb:150:in `setup'
        from /home/elias9vx5/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/setup.rb:20:in `block in <top (required)>'
        from /home/elias9vx5/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/ui/shell.rb:136:in `with_level'
        from /home/elias9vx5/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/ui/shell.rb:88:in `silence'
        from /home/elias9vx5/.rbenv/versions/3.0.3/lib/ruby/3.0.0/bundler/setup.rb:20:in `<top (required)>'
        from <internal:/home/elias9vx5/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/elias9vx5/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
I have msf starting up with beef

**Comment by OrangeGlowest** [comment]
When I type these gems, it is saying gem not found
