### ISSUE TITLE
Error in console and 500 error on hook.js

### ISSUE THREAD

**Issue by konn-neko** [beefproject/beef#2931]
## First Steps

1. Confirmed that my issue has not been posted previously
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version: 0.5.4.0
5. Ruby Version: 3.0.3
6. Browser Details (e.g. Chrome v81.0): chrome unknown ver
7. Operating System (e.g. OSX Catalina): android and windows, so prob everyhting

## Configuration

1. Have you made any changes to your BeEF configuration? yes, 
2. Have you enabled or disabled any BeEF extensions? no

## Steps to Reproduce

1. run ./beef, works fine
2. have device connect, errors with error 
```
ArgumentError - invalid byte sequence in US-ASCII:
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `scan'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/erubis-2.7.0/lib/erubis/enhancer.rb:647:in `convert_input'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/erubis-2.7.0/lib/erubis/converter.rb:36:in `convert'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/erubis-2.7.0/lib/erubis/engine.rb:30:in `initialize'
        /root/beef/core/main/handlers/modules/legacybeefjs.rb:104:in `new'
        /root/beef/core/main/handlers/modules/legacybeefjs.rb:104:in `legacy_build_beefjs!'
        /root/beef/core/main/handlers/hookedbrowsers.rb:138:in `block in <class:HookedBrowsers>'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `call'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1706:in `block in compile!'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1019:in `block (3 levels) in route!'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1037:in `route_eval'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1019:in `block (2 levels) in route!'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1068:in `block in process_route'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `catch'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1066:in `process_route'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1017:in `block in route!'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1014:in `each'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1014:in `route!'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1138:in `block in dispatch!'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `catch'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `invoke'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1133:in `dispatch!'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:949:in `block in call!'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `catch'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:1109:in `invoke'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:949:in `call!'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:938:in `call'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.8/lib/rack/null_logger.rb:11:in `call'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:219:in `call'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-3.0.6/lib/sinatra/base.rb:2018:in `call'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.8/lib/rack/urlmap.rb:74:in `block in call'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.8/lib/rack/urlmap.rb:58:in `each'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.8/lib/rack/urlmap.rb:58:in `call'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/connection.rb:86:in `block in pre_process'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/connection.rb:84:in `catch'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/connection.rb:84:in `pre_process'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/connection.rb:53:in `process'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/connection.rb:39:in `receive_data'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/backends/base.rb:75:in `start'
        /root/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thin-1.8.2/lib/thin/server.rb:162:in `start'
        /root/beef/core/main/server.rb:156:in `start'
        ./beef:278:in `<main>'
```
![image](https://github.com/beefproject/beef/assets/92604391/36f732b3-6bf3-4ac1-8c14-939c0390dda8)
**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by bcoles** [comment]
> ArgumentError - invalid byte sequence in US-ASCII:

https://github.com/beefproject/beef/wiki/FAQ#how-do-i-fix-argumenterror---invalid-byte-sequence-in-us-ascii-
