### ISSUE TITLE
Error when someone connecting

### ISSUE THREAD

**Issue by KryaKryaDUCK** [beefproject/beef#3029]
```
When someone connecting it says error: 
#<Thread:0x00007f7b2c1c5508 /home/vovanchik/stuff/beef-master/extensions/proxy/proxy.rb:53 run> terminated with exception (report_on_exception is true):
/usr/lib/ruby/3.1.0/openssl/buffering.rb:80:in `sysread': SSL session is not started yet (OpenSSL::SSL::SSLError)
	from /usr/lib/ruby/3.1.0/openssl/buffering.rb:80:in `fill_rbuff'
	from /usr/lib/ruby/3.1.0/openssl/buffering.rb:332:in `eof?'
	from /usr/lib/ruby/3.1.0/openssl/buffering.rb:285:in `readline'
	from /home/vovanchik/stuff/beef-master/extensions/proxy/proxy.rb:54:in `handle_request'

After this error, admin panel says me that framework is down.

How do i fix that?

BeEF Version: Latest
Ruby Version: 3.1.2p20
Browser: Firefox 123
Operating System: Linux Ubuntu 23.10


```

**Comment by bcoles** [comment]
It looks like you are connecting to the proxy server on port 6789.

BeEF runs on port 3000 by default.

**Comment by KryaKryaDUCK** [comment]
How do i change ports 3000 and 6789? Need to change them because i keep getting error.
