### ISSUE TITLE
Browserstack is failing to run PR check

### ISSUE THREAD

**Issue by zinduolis** [beefproject/beef#3172]
## First Steps

1. Confirm that your issue has not been posted previously by searching here: https://github.com/beefproject/beef/issues
2. Confirm that the wiki does not contain the answers you seek: https://github.com/beefproject/beef/wiki
3. Check the FAQ: https://github.com/beefproject/beef/wiki/FAQ
4. BeEF Version: 0.5.4.0
5. Ruby Version: ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux-gnu]
6. Browser Details (e.g. Chrome v81.0): N/A
7. Operating System (e.g. OSX Catalina): Ubuntu 24

## Configuration

1. Have you made any changes to your BeEF configuration? No
2. Have you enabled or disabled any BeEF extensions? No

## Steps to Reproduce

1. This is an example of the failed run on a PR: https://github.com/beefproject/beef/actions/runs/11399551484/job/31718551736?pr=3149
2. To reproduce using a command line tool, navigate to beef folder and run the following command from there: `bundle exec rake browserstack --trace`
4. Here is a snippet of results:

```
Browser hooking with Websockets
[17:14:30][*] Loading database
[17:14:30][*] Resetting the database for BeEF.
[17:14:30][*] Loading in BeEF::Extensions
[17:14:30][*] Loading in BeEF::Modules
  confirms a websocket server has been started (FAILED - 1)
  confirms a secure websocket server has been started (FAILED - 2)
  can successfully hook a browser (FAILED - 3)
[17:14:30][*] Exception: undefined method `quit' for nil:NilClass
[17:14:30][*] Exception Class: NoMethodError
[17:14:30][*] Exception Message: undefined method `quit' for nil:NilClass
[17:14:30][*] Exception Stack Trace: ["/home/zinduolis/repos/beef/spec/spec_helper.rb:88:in `server_teardown'", "/home/zinduolis/repos/beef/spec/beef/extensions/websocket_hooked_browser_spec.rb:92:in `block (2 levels) in <top (required)>'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/hooks.rb:381:in `instance_exec'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/hooks.rb:381:in `run'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/hooks.rb:528:in `each'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/hooks.rb:480:in `run'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example_group.rb:591:in `block in run_after_context_hooks'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/memoized_helpers.rb:208:in `block in isolate_for_context_hook'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/memoized_helpers.rb:204:in `instance_exec'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/memoized_helpers.rb:204:in `isolate_for_context_hook'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example_group.rb:590:in `run_after_context_hooks'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/example_group.rb:619:in `run'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:121:in `map'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/configuration.rb:2092:in `with_suite_hooks'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:116:in `block in run_specs'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/reporter.rb:74:in `report'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:115:in `run_specs'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:89:in `run'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:71:in `run'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/lib/rspec/core/runner.rb:45:in `invoke'", "/var/lib/gems/3.2.0/gems/rspec-core-3.13.1/exe/rspec:4:in `<main>'"]
[17:14:30][*] Shutting down server
 
An error occurred in an `after(:context)` hook.
Failure/Error: Process.kill('KILL', server_pid)

TypeError:
  no implicit conversion from nil to integer
# ./spec/spec_helper.rb:97:in `kill'
# ./spec/spec_helper.rb:97:in `ensure in server_teardown'
# ./spec/spec_helper.rb:98:in `server_teardown'
# ./spec/beef/extensions/websocket_hooked_browser_spec.rb:92:in `block (2 levels) in <top (required)>'
# ------------------
# --- Caused by: ---
# NoMethodError:
#   undefined method `quit' for nil:NilClass
#   ./spec/spec_helper.rb:88:in `server_teardown'

```

## How to enable and capture detailed logging

1. Edit `config.yaml` in the root directory
   * If using Kali **beef-xss** the root dir will be  `/usr/share/beef-xss`
5. Update `client_debug` to `true`
6. Retrieve browser logs from your browser's developer console (Ctrl + Shift + I or F12 depending on browser)
7. Retrieve your server-side logs from `~/.beef/beef.log`
   * If using **beef-xss** logs found with `journalctl -u beef-xss`

**If we request additional information and we don't hear back from you within a week, we will be closing the ticket off.**

**Comment by zinduolis** [comment]
Investigating

**Comment by zinduolis** [comment]
https://www.browserstack.com/docs/automate/selenium/getting-started/ruby/integrate-your-tests
