### ISSUE TITLE
I've searching and debugging since 10Am and cant find the solution

### ISSUE THREAD

**Issue by lucachala** [beefproject/beef#3218]
System:
Brand new Nanode from linode with kali-linux

This is what I got, before it was a missing sqlite, fixed that and now this. fml

<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /var/lib/gems/3.1.0/gems/sqlite3-2.2.0-x86_64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
        from /var/lib/gems/3.1.0/gems/sqlite3-2.2.0-x86_64-linux/lib/sqlite3.rb:2:in `<top (required)>'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:60:in `require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:55:in `each'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:55:in `block in require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `each'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler.rb:187:in `require'
        from /root/beef/core/loader.rb:16:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from ./beef:45:in `<main>'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require': /lib/x86_64-linux-gnu/libc.so: invalid ELF header - /var/lib/gems/3.1.0/gems/sqlite3-2.2.0-x86_64-linux/lib/sqlite3/3.1/sqlite3_native.so (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /var/lib/gems/3.1.0/gems/sqlite3-2.2.0-x86_64-linux/lib/sqlite3.rb:4:in `<top (required)>'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:60:in `require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:55:in `each'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:55:in `block in require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `each'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler.rb:187:in `require'
        from /root/beef/core/loader.rb:16:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from ./beef:45:in `<main>'

**Comment by lucachala** [comment]
Changed Gemfile to sqlite3 v1.4 it worked

**Comment by bichou** [comment]
> Changed Gemfile to sqlite3 v1.4 it worked

1.6 work too

**Comment by lucachala** [comment]
Maybe it's only not working on the "default" version. Perhaps a problem with compatability with other gems

**Comment by stephenakq** [comment]
Please join the BeEF discord to discuss this issue. Someone there might be able to help https://discord.gg/ugmKmHarKc
