### ISSUE TITLE
Cannot load such file -- sqlite3/sqlite3_native

### ISSUE THREAD

**Issue by thatwaseasy3** [beefproject/beef#3254]
Hello guys, I am new here, despite all my attempts I cannot solve this problem. I use Kali Linux and I can't run Beef, despite all the updates I have made it, I would be glad if you could help me, thank you.

<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /var/lib/gems/3.1.0/gems/sqlite3-2.5.0-x86_64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
        from /var/lib/gems/3.1.0/gems/sqlite3-2.5.0-x86_64-linux/lib/sqlite3.rb:2:in `<top (required)>'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:60:in `require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:55:in `each'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:55:in `block in require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `each'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler.rb:187:in `require'
        from /home/kali/beef/core/loader.rb:16:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from ./beef:45:in `<main>'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require': /lib/x86_64-linux-gnu/libc.so: invalid ELF header - /var/lib/gems/3.1.0/gems/sqlite3-2.5.0-x86_64-linux/lib/sqlite3/3.1/sqlite3_native.so (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /var/lib/gems/3.1.0/gems/sqlite3-2.5.0-x86_64-linux/lib/sqlite3.rb:4:in `<top (required)>'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:60:in `require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:55:in `each'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:55:in `block in require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `each'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/runtime.rb:44:in `require'
        from /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler.rb:187:in `require'
        from /home/kali/beef/core/loader.rb:16:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from ./beef:45:in `<main>'

**Comment by DikkeMuis** [comment]
i have the same issue

**Comment by ravi13dayyala** [comment]
facing same issue on  kali, not sure if its an issue with sqlite3.

**Comment by ravi13dayyala** [comment]
Hi, Its working for me after downgrading sqlite3's version in Gemfile from 2.5 to 1.4
'sqlite3', '~> 1.4'

**Comment by mohmadamarnh** [comment]
> Hi, Its working for me after downgrading sqlite3's version in Gemfile from 2.5 to 1.4 'sqlite3', '~> 1.4'

Can you guide us please

**Comment by Strikenfield** [comment]
Same issue.
Please guide to fix it

**Comment by ravi13dayyala** [comment]
Hi, Sorry I haven't seen your replies.

1) Just clone the beef repo.

2) cd beef/

3) Open the 'Gemfile' and change the version of sqlite3 from 2.5 to 1.4.  like below. (Line no.  26)


'sqlite3', '~> 1.4'


4) ./install

5) change credentials in config.yaml

6) ./beef
